### ISSUE TITLE
如果需要跳转打开新其他页面，会被拦截，如何获取页面的新的红点消息，传到app外面提示红点

### ISSUE THREAD

**Issue by yingnierxiao** [tw93/Pake#107]
补充一个问题，如果关闭的时候最小化到菜单栏，和状态栏，而不是直接退出应用

**Comment by tw93** [comment]
补充问题是故意这样设计的，强制关闭一般用 command ➕ q
跳转打开新页面，可以参考下pake js 里面代码 ，有一个跳转兼容

**Comment by yingnierxiao** [comment]
> 补充问题是故意这样设计的，强制关闭一般用 command ➕ q
> 跳转打开新页面，可以参考下pake js 里面代码 ，有一个跳转兼容
> 此外你是哪一个APP

公司的im 网页版本，经常把网页关闭了，所以想用你这个项目包一下，独立开来，不会不小心关了

**Comment by tw93** [comment]
哦哦，你可以看看我上面说的这个，看一下公司项目的外跳方式，然后用js去拦截即可，可以在里面打开，也可以打开默认浏览器的方式
