### ISSUE TITLE
下载msi安装之后闪退 windows版本是11

### ISSUE THREAD

**Issue by 2021Kfzz1** [tw93/Pake#114]

**Comment by tw93** [comment]
请问是这个问题吗？
> 注意：Windows 下不能安装到 C:\Program File，会直接闪退，建议安装到其他非管理员权限目录，比如 D:\Program Files (x86) 。

**Comment by 2021Kfzz1** [comment]
我都进行了尝试，用的是您的releases，安装之后一直闪退

**Comment by tw93** [comment]
@Tlntin 看看

**Comment by 2021Kfzz1** [comment]
一定要是D:\Program Files (x86)这个文件夹吗

**Comment by tw93** [comment]
先试试看，因为我的电脑是mac🐶

**Comment by 2021Kfzz1** [comment]
好了，谢谢，但是youtube这些需要代理的打不开

**Comment by 2021Kfzz1** [comment]
好的谢谢
