### ISSUE TITLE
mac big sur 

### ISSUE THREAD

**Issue by cnmeeia** [tw93/Pake#116]
error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-Wall" "-Wextra" "-fmodules" "-Wno-deprecated-declarations" "-mmacos-version-min=10.13" "-o" "/usr/local/lib/node_modules/pake-cli/src-tauri/target/aarch64-apple-darwin/release/build/mac-notification-sys-d3684fe1a769bf14/out/objc/notify.o" "-c" "objc/notify.m" with args "cc" did not execute successfully (status code exit status: 1).

Error: 1
    at file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1:14109
    at /usr/local/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:420:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)

**Comment by tw93** [comment]
看到这句
mmacos-version-min=10.13
你的mac版本是多少？

**Comment by cnmeeia** [comment]
> 看到这句
> 
> mmacos-version-min=10.13
> 
> 你的mac版本是多少？

我的系统是 big sur 11.7

**Comment by jackluson** [comment]
> 
这个问题怎么解决了呢，是升级系统吗
