### ISSUE TITLE
建议：所有外链新窗口打开

### ISSUE THREAD

**Issue by vipzhicheng** [tw93/Pake#128]
希望可以内置这个特性，比如看Twitter的时候，经常会点击里面的外链，但是在webview内部打开再退回去的时候就丢失了之前的位置。

**Comment by tw93** [comment]
哦哦 你是下载的最新包吗？最新包，twitter 我默认浏览器打开了

**Comment by tw93** [comment]
done 已经支持，等到发布新包即可
