### ISSUE TITLE
关于返回操作

### ISSUE THREAD

**Issue by liusishan** [tw93/Pake#13]
可以加一个返回操作吗，也就是浏览器的后退。如果能收拾操作就更好了

**Comment by tw93** [comment]
安排，做了通知你，是一个通用的功能

**Comment by liusishan** [comment]
好的 真是感谢！

**Comment by tw93** [comment]
支持了
command + ←：返回上一个页面
command + →：去下一个页面，假如有的话
command + ↑：自动滚动到页面顶部
command + ↓：自动滚动到页面底部
command + r：刷新页面

可以去readme中找到下载地址，下载最新的版本
