### ISSUE TITLE
Cannot set properties of null (setting 'peer')  报错

### ISSUE THREAD

**Issue by sydeEvans** [tw93/Pake#136]
$ pake https://www.baidu.com --transparent
now platform is  darwin
✔ please input your application name … baidu
You have not provided an app icon, use the default icon.(use --icon option to assign an icon)
npm ERR! Cannot set properties of null (setting 'peer')

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/evans/.npm/_logs/2022-12-07T03_42_21_515Z-debug-0.log
file:///Users/evans/.nvm/versions/node/v16.14.2/lib/node_modules/pake-cli/dist/cli.js:1786
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///Users/evans/.nvm/versions/node/v16.14.2/lib/node_modules/pake-cli/dist/cli.js:1786:24
    at /Users/evans/.nvm/versions/node/v16.14.2/lib/node_modules/pake-cli/node_modules/_shelljs@0.8.5@shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by wanghanzhen** [comment]
看起来像是npmcli的bug https://github.com/npm/cli/issues/3711
试试删node_modules或者npm uninstall后重新安装呢？

**Comment by niuhuheyi** [comment]
ok thank you  good

**Comment by tw93** [comment]
一个问题 参考这里
https://github.com/tw93/Pake/issues/132#issuecomment-1345753887

**Comment by niuhuheyi** [comment]
good  verygood thankyou
