### ISSUE TITLE
🔴 「Google Podcasts」申请适配

### ISSUE THREAD

**Issue by Thomas-Harrell** [tw93/Pake#137]
## Google Podcasts

https://podcasts.google.com/

试过用 NPM 命令打包网站了，但是 M1 Mac 在最后打包的时候会报错，顺着路径也找不到 DMG 包

**Comment by icelo0** [comment]
我出现了和你一样的问题，而且我添加了图标也是一样的报错，我的是mac-Intel，报错情况如下：

$ pake https://www.baidu.com --icon '/Users/iei/Documents/r.icns' --name 'Rebang'
now platform is  darwin
✔ We detected that you have not installed Rust. Install it now? … yes
⠦ Downloading Rustinfo: downloading installer
⠸ Downloading Rustinfo: profile set to 'default'
info: default host triple is x86_64-apple-darwin
warning: Updating existing toolchain, profile choice will be ignored
⠧ Downloading Rustinfo: syncing channel updates for 'stable-x86_64-apple-darwin'
⠴ Downloading Rustinfo: default toolchain set to 'stable-x86_64-apple-darwin'

⠦ Downloading Rust  stable-x86_64-apple-darwin unchanged - rustc 1.65.0 (897e37553 2022-11-02)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
✔ Downloading Rust
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

added 82 packages, and audited 235 packages in 2m

76 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> pake-cli@0.1.1 build:release
> npm run tauri build --release


> pake-cli@0.1.1 tauri
> tauri build

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, copyfile '/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/dmg/Rebang_1.0.0_x64.dmg' -> '/Users/ilei/Documents/Rebang.dmg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/dmg/Rebang_1.0.0_x64.dmg',
  dest: '/Users/ilei/Documents/Rebang.dmg'
}

Node.js v18.10.0

**Comment by tw93** [comment]
这一块我们还是全面兼容一下 避免边界情况

**Comment by icelo0** [comment]
> @icelo0
> 图标试试当前终端所在的相对路径。



我改成相对路径还是一样的，不知道是什么问题。还请帮忙排查一下


```
$ pake https://www.baidu.com --icon './r.icns' --name 'Rebang'
now platform is  darwin
✔ We detected that you have not installed Rust. Install it now? … yes
⠏ Downloading Rustinfo: downloading installer
⠧ Downloading Rustinfo: profile set to 'default'
info: default host triple is x86_64-apple-darwin
warning: Updating existing toolchain, profile choice will be ignored
⠏ Downloading Rustinfo: syncing channel updates for 'stable-x86_64-apple-darwin'
⠹ Downloading Rustinfo: default toolchain set to 'stable-x86_64-apple-darwin'

⠸ Downloading Rust  stable-x86_64-apple-darwin unchanged - rustc 1.65.0 (897e37553 2022-11-02)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
✔ Downloading Rust

up to date, audited 235 packages in 2s

76 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> pake-cli@0.1.1 build:release
> npm run tauri build --release


> pake-cli@0.1.1 tauri
> tauri build

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, copyfile '/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/dmg/Rebang_1.0.0_x64.dmg' -> '/Users/ilei/Documents/Rebang.dmg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/dmg/Rebang_1.0.0_x64.dmg',
  dest: '/Users/ilei/Documents/Rebang.dmg'
}

Node.js v18.10.0
```

**Comment by icelo0** [comment]
@Tlntin 

修改成小写后我依旧报错，如下：

```
$ pake https://www.baidu.com --icon ./r.icns --name baidu
now platform is  darwin
✔ We detected that you have not installed Rust. Install it now? … yes
⠴ Downloading Rustinfo: downloading installer
⠴ Downloading Rustinfo: profile set to 'default'
info: default host triple is x86_64-apple-darwin
warning: Updating existing toolchain, profile choice will be ignored
⠇ Downloading Rustinfo: syncing channel updates for 'stable-x86_64-apple-darwin'
⠦ Downloading Rustinfo: default toolchain set to 'stable-x86_64-apple-darwin'

⠧ Downloading Rust  stable-x86_64-apple-darwin unchanged - rustc 1.65.0 (897e37553 2022-11-02)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
✔ Downloading Rust

up to date, audited 235 packages in 2s

76 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> pake-cli@0.1.1 build:release
> npm run tauri build --release


> pake-cli@0.1.1 tauri
> tauri build

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/interface/rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, copyfile '/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/dmg/baidu_1.0.0_x64.dmg' -> '/Users/ilei/Documents/baidu.dmg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/dmg/baidu_1.0.0_x64.dmg',
  dest: '/Users/ilei/Documents/baidu.dmg'
}

Node.js v18.10.0
```

**Comment by meng8131** [comment]
> 

@Tlntin 能分享下命令么? 我用来练练手, 另外换个icon, 多谢
