### ISSUE TITLE
M1 MacBook打包问题

### ISSUE THREAD

**Issue by iinux** [tw93/Pake#14]
Error failed to build x86_64-apple-darwin binary: Target x86_64-apple-darwin is not installed (installed targets: aarch64-apple-darwin). Please run `rustup target add x86_64-apple-darwin`.

目前是不能打 apple silicon 的包吗？

**Comment by tw93** [comment]
可以的，第一次你需要按照他的提示来安装包
`rustup target add x86_64-apple-darwin`
