### ISSUE TITLE
Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

### ISSUE THREAD

**Issue by hktalent** [tw93/Pake#147]
Mac OS

pake https://xxx.com --name xxx --transparent --icon static/img/bleve.png

up to date, audited 235 packages in 1s

76 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> pake-cli@0.1.2 build
> npm run tauri build --release

> pake-cli@0.1.2 tauri
> tauri "build"

    Updating crates.io index
error: Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to authenticate when downloading repository: ssh://git@github.com/rust-lang/crates.io-index

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  no authentication available
       Error failed to build app: failed to build app
file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1793
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1793:24
    at /usr/local/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by tw93** [comment]
错误在这里failed to fetch https://github.com/rust-lang/crates.io-index
谷歌搜索设置国内 rust 镜像即可

**Comment by hktalent** [comment]
```

   Compiling app v0.1.0 (/usr/local/lib/node_modules/pake-cli/src-tauri)
    Finished release [optimized] target(s) in 14.50s
    Bundling 51pwn.app (/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/macos/51pwn.app)
    Bundling 51pwn_1.0.0_x64.dmg (/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/dmg/51pwn_1.0.0_x64.dmg)
     Running bundle_dmg.sh
       Error failed to bundle project: error running bundle_dmg.sh: error running bundle_dmg.sh: `failed to run /usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/dmg/bundle_dmg.sh`
file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1794
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1794:24
    at /usr/local/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:146:9
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12)
```
