### ISSUE TITLE
Apps do not restore their window state when reopening

### ISSUE THREAD

**Issue by Poopooracoocoo** [tw93/Pake#164]
Tested with Qwety Learner and YouTube.

Steps to repro:
1. Install an app
2. Resize or move window
3. Close and reopen

Expected behaviour:
App opens window at same position and size it was closed 

Actual behaviour:
App resets window position and size. This is especially bad because part of the window is offscreen on my display.

Note:
I think Tauri requires https://github.com/tauri-apps/tauri-plugin-window-state for some reason. I don't know why it's a separate plugin...

**Comment by tw93** [comment]
Version 2.0 is already supported and has recently been refactored. It will be available in the upcoming release.
