### ISSUE TITLE
WhatsApp 提示需要 Safari11 +

### ISSUE THREAD

**Issue by NoirJ0e** [tw93/Pake#17]
系统： macOS Monterey 12.6
处理器：M1 Pro

问题：

下载并运行提供的 WhatsApp 包后，提示 WhatsApp works with Safari 11+ 并提示升级浏览器

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/60462008/196339028-9d00524a-7aaf-4089-80d7-146486508cc6.png">

其他提供的示例 app 并没有遇到此问题

**Comment by tw93** [comment]
谢谢反馈

**Comment by NoirJ0e** [comment]
我尝试自己生成了一个也是遇到了一样的提示，换用 [nativefier](https://github.com/nativefier/nativefier) 后可以正常生成并开始使用

**Comment by tw93** [comment]
试试看用你的safari打开，是否也是一样的提示哦

**Comment by NoirJ0e** [comment]
使用系统自带的Safari打开 web.whatsapp.com ，可以正常显示和使用，没有问题
自带的Safari 信息：
<img width="396" alt="image" src="https://user-images.githubusercontent.com/60462008/196380710-169a1e13-d419-4c3e-a08f-9c0346683590.png">

**Comment by tw93** [comment]
辛苦试试这个，我将依赖全部更新到最新了，我这边由于电脑原因，不能访问WhatsApp，请谅解
[Whatsapp_0.1.0_universal.dmg.zip](https://github.com/tw93/Pake/files/9808835/Whatsapp_0.1.0_universal.dmg.zip)

**Comment by tw93** [comment]
嗯嗯 欢迎欢迎，解决了欢迎提pr，这个我先关闭了

**Comment by NoirJ0e** [comment]
抱歉又把这个顶上来，应该是 wry 默认的 userAgent 缺少了版本信息导致一些网站无法准确判断导致的这个问题，对 rust 相当不熟悉暂时没办法去自己修复了。

Link: https://github.com/tauri-apps/tauri/discussions/3519

**Comment by tw93** [comment]
https://github.com/tauri-apps/tauri/issues/4284
看到这个，看起来1.2版本会支持，现在tauri是1.1.1版本，应该快了
同样你可以参考这里面有同学的解法试试看

**Comment by dickwu** [comment]
这个问题还没修复吗 tauri 已经 1.2.1 了

**Comment by LiXin-x** [comment]
同样打包阿里云盘，看视频网页版有全屏，pake 1.01 打出来没有这个全屏按钮
