### ISSUE TITLE
关于http对的支持

### ISSUE THREAD

**Issue by tanwenchao** [tw93/Pake#171]
大佬，能支持http协议的吗，或者说在哪儿配置？

**Comment by tw93** [comment]
默认应该是支持的，你试试看

**Comment by jaysoncho92** [comment]
mac m1电脑上尝试一键打包，https的app能正常打开，http的app打开后页面一直是空白的，是什么原因？

> 默认应该是支持的，你试试看

**Comment by tw93** [comment]
给一个页面 我调试下看看

**Comment by jaysoncho92** [comment]
> 给一个页面 我调试下看看
我在常用包那边下载了mac版的qwerty，在mac m1上无法打开，自己一键打包后app页面是空白的。
http://qwerty.liumingye.cn/

**Comment by tw93** [comment]
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/8736212/208018197-eb467d04-9a42-4d49-b3d5-d534c553ea46.png">
我这边OK，你试试用safari打开看看

**Comment by tw93** [comment]
先关闭下，这一块辛苦再试试复现

**Comment by tanwenchao** [comment]
http://tanwenchao.com/

哈喽大佬，我用我自己的个人网站一键打包后也是空白的，macOS
