### ISSUE TITLE
更改窗口外观

### ISSUE THREAD

**Issue by SHEN-Muchuan** [tw93/Pake#18]
我目前使用的是 Pake 的竞品之一 Nativefier。相比之下，Pake 的内存占用显然更小。

但是有一个比较重要的功能感觉还是缺失的，就是自定义窗口外观，Nativefier 可以设置 browserwindow-option ，来实现移动红绿灯位置，以及 macOS 系统的窗口毛玻璃效果。

不过这些功能是基于 electron 的 API, 不知道 Tauri 能否实现。

**Comment by tw93** [comment]
当前支持这些
https://tauri.app/v1/api/config#windowconfig

假如想更高级的就需要自己去底层实现了 方便说说主要需要改的原因吗
