### ISSUE TITLE
window 已经安装完毕pake-cli，识别不了pake命令，是需要进入pake-cli么

### ISSUE THREAD

**Issue by jcgfxk** [tw93/Pake#184]
![image](https://user-images.githubusercontent.com/7160787/208394169-7ba052e1-58c8-412c-9ed9-64985578dcbe.png)
不好意思，耽误您宝贵的时间

**Comment by tw93** [comment]
客气了 看起来是windows的一个限制，你需要配置下
https://answers.microsoft.com/zh-hans/windows/forum/all/%E6%97%A0%E6%B3%95%E5%B0%86sfc%E9%A1%B9%E8%AF%86/667871b7-2b29-4d4a-bf9a-51cc1edfc2f0

可以可以谷歌关键词看看

**Comment by jcgfxk** [comment]
> 客气了 看起来是windows的一个限制，你需要配置下 https://answers.microsoft.com/zh-hans/windows/forum/all/%E6%97%A0%E6%B3%95%E5%B0%86sfc%E9%A1%B9%E8%AF%86/667871b7-2b29-4d4a-bf9a-51cc1edfc2f0
> 
> 可以可以谷歌关键词看看

真诚感谢，已经通过添加环境变量识别了pake
