### ISSUE TITLE
简单探讨

### ISSUE THREAD

**Issue by zwmmm** [tw93/Pake#19]
可以看出内部是使用iframe嵌套网页的形式，这种方案对比 pwd 和 直接在浏览器打开有什么优点么，我下载了
微信读书，感觉和用浏览器没区别啊，打开会有一段时间白屏

**Comment by tw93** [comment]
其实可以理解是用的系统webkit的能力在做一个很轻量的套壳app，其实喜欢浏览器的方式的同学完全没有必要用这个工具，这个工具适合比如有些场景，比如说按理这个工具需要有一个mac版本但是没有的那种强迫症同学使用，同时轻一点而已
 
关于使用场景，其实可以参考这个 https://github.com/nativefier/nativefier 这个工具，他比pake做得要完善很多，不过他用的是之前我们常用的Electron套壳的思路而已
