### ISSUE TITLE
项目的lisence以及发布二进制到app store

### ISSUE THREAD

**Issue by kidylee** [tw93/Pake#194]
很喜欢这个项目，想问一下目前项目的lisence，可能会引用部分代码或者作为我个人项目的上游依赖使用，所以想先确认一下lisence。

另外是否考虑将部分二进制分发到诸如mac app store，当然优先考虑没有版权纠纷的部分。

**Comment by tw93** [comment]
不允许分发到app store哦 因为我这边也在准备这个事情
此外代码参考问题不大。
