### ISSUE TITLE
求支持即刻/饭否

### ISSUE THREAD

**Issue by meng8131** [tw93/Pake#20]

**Comment by tw93** [comment]
[饭否.dmg.zip](https://github.com/tw93/Pake/files/9808450/dmg.zip)
[即刻.dmg.zip](https://github.com/tw93/Pake/files/9808452/dmg.zip)
谢谢喜欢，去玩吧~

**Comment by meng8131** [comment]
> [饭否.dmg.zip](https://github.com/tw93/Pake/files/9808450/dmg.zip) [即刻.dmg.zip](https://github.com/tw93/Pake/files/9808452/dmg.zip) 谢谢喜欢，去玩吧~

@tw93 
感恩

ღ( ´･ᴗ･` )比心

**Comment by meng8131** [comment]
反馈个[即刻]的问题
<img width="762" alt="image" src="https://user-images.githubusercontent.com/14783482/196583030-9c7737c0-2bcd-4a88-bf36-30cf8ad4e651.png">

**Comment by meng8131** [comment]
神速 👍👍👍
