### ISSUE TITLE
Could not enable Mach bootstrap

### ISSUE THREAD

**Issue by sirius60111** [tw93/Pake#217]
打包了 Mac 的飞书云文档 https://www.feishu.cn/drive/home，点击某个文档的时候没有反应，console 里报错：
```
Subsystem: com.apple Webkit Category: Sandbox
Could not enable Mach bootstrap, errno = 1.
```
MacOS: Ventura 13.1
Pake: V1.0.1

**Comment by tw93** [comment]
这里我试了试  飞书云文档使用的 window.open 类似方法，有办法hack，不过飞书本身实现有些问题，后面看看怎么支持比较好

**Comment by tw93** [comment]
试了试飞书自己的处理还是有些问题，不建议用这个打包好了，飞书在Pake下面体验比较差
