### ISSUE TITLE
How to enable pop-up opening?

### ISSUE THREAD

**Issue by justLuiz** [tw93/Pake#218]
How to enable pop-up opening?

When a APP try `window.open`, nothing happens

(Ex Login with Google or others)

**Comment by tw93** [comment]
I will try it😀

**Comment by youbaowangsheng** [comment]
我看作者自己打包好的app是支持pop-up的。但是自己打包的不行。

**Comment by tw93** [comment]
@youbaowangsheng Which app? Let me see.

**Comment by tw93** [comment]
Finally, I tried and passed `.with_ new_ window_ req_handler`, but unexpected errors may occur, Currently not supported, wait for the underlying framework to see how it can be supported
