### ISSUE TITLE
预制/示例包可以放在 release 中，不一定要 check in

### ISSUE THREAD

**Issue by bnoctis** [tw93/Pake#22]
release assets 是可以手动增删的，点 release 右上角的笔图标就行。

**Comment by tw93** [comment]
很感谢反馈，我之前误以为每次release需要制定版本有些麻烦，查了查 原来支持  https://github.com/tw93/Pake/releases/latest/download/WeRead.dmg 这样的方式，已经迁移
https://github.com/tw93/Pake/releases

**Comment by tw93** [comment]
谢谢 学习到了 明天我试试
