### ISSUE TITLE
打包失败，找不到文件

### ISSUE THREAD

**Issue by vangogogo** [tw93/Pake#228]
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/5194254/210942959-1a329fc9-a39b-4a77-a16d-da8baa29c822.png">
系统 macOS:13.1 (22C65)
npm：6.14.15
node:14.18.2

**Comment by vangogogo** [comment]
M1pro 14''

**Comment by tw93** [comment]
直接试试 node 16 版本以上的，然后可以更新pake-cli到最新的1.2.1  再看看~

**Comment by chao-eng** [comment]
M2

**Comment by harwinvoid** [comment]
![image](https://user-images.githubusercontent.com/12931494/222713535-1f216d4e-0a3b-44af-9d7c-1d3b807de308.png)
依然存在这个问题。
mac mini M2

**Comment by tw93** [comment]
看起来是 rust 安装失败了，重装一下即可
