### ISSUE TITLE
非80，443端口，打开页面空白

### ISSUE THREAD

**Issue by vangogogo** [tw93/Pake#233]
非标准端口，比如8080，7788之类，页面无法打开是空白，不知道如何调试，无法得知具体原因。
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/5194254/211145023-95fd71d4-35e2-4fe7-addb-4457d4b3c75f.png">

**Comment by tw93** [comment]
可以试试这些页面 safari 是否可以打开，此外可以clone项目，直接参考高级模式，然后替换url，npm run dev:debug 就可以调试

**Comment by tw93** [comment]
先关闭哦，以后还有问题继续打开就好~
