### ISSUE TITLE
Translation of readme in english

### ISSUE THREAD

**Issue by RoHit4100** [tw93/Pake#235]
Only english would be better choice to create readme.

**Comment by tw93** [comment]
You can see this document https://github.com/tw93/Pake/blob/master/README_EN.md
If the translation is wrong, please point out, Thank you.🤟

**Comment by tw93** [comment]
I don't know whether you are interested in Pake or not. You are welcome to join in and help with internationalization

**Comment by RoHit4100** [comment]
Of course I am interested pake sir.... Thank you for the welcome 🎉It means alot!

**Comment by tw93** [comment]
If you have how to update and optimize, you can directly submit the pr🎉

**Comment by RoHit4100** [comment]
Exactly 🎉
