### ISSUE TITLE
受 Tauri 安全限制，webview 中的链接会失效

### ISSUE THREAD

**Issue by lencx** [tw93/Pake#24]
如果网站中包含 `<a href="xxx" target="_blank">xxx</a>` 或使用 `window.open` 之类的新开窗口，会被 Tauri 阻止。

---

我也在做类似构建，使用 `tauri::WindowBuilder::new` API 也遇到了类似问题，欢迎交流。
仓库：https://github.com/lencx/WA

**Comment by tw93** [comment]
其实有解法，注入js，改写链接跳转方式即可

**Comment by lencx** [comment]
我们早上就聊到了这种方式，如果要改写所有新开窗口的方式，注入脚本可靠吗？有些可能是通过事件触发的。![image](https://user-images.githubusercontent.com/16164244/196658062-54fc83f6-bbd1-4c0c-a491-54375d15c5ea.png)

**Comment by tw93** [comment]
这个pake已经实现了 
话说有兴趣一起来建设pake不 我拉你进群

**Comment by lencx** [comment]
可以呀，我也在搞类似的事情

**Comment by tw93** [comment]
我的 tg 号是 Hitw93，你加我一下，我拉你进群

**Comment by lencx** [comment]
好的，谢谢

**Comment by fakeYanss** [comment]
我看很多issue都聊了可以注入，但是我不熟悉js，在这里也查了挺久才解决的。

最开始是监听click事件，找到点击的这个dom元素的跳转目标地址，然后 `window.eval("window.location.replace('" + url + "')")` 更新当前页的地址。

后来发现可以重写全局的window.open方法，更简单
```
window.open = function (open) {
  return function (url, name, features) {
    window.top.location = url;
    return false;
  };
}(window.open);
```
