### ISSUE TITLE
重新搜索后，已经展开的词条没有reset

### ISSUE THREAD

**Issue by siyuyang** [tw93/Pake#243]
https://user-images.githubusercontent.com/39404000/211261807-2fbbf5de-eeb9-4bfd-a413-1d584d4b6240.mov

To reproduce:
1. search something
2. expand one of the results
3. search something else
4. unexpected behavior - the expanded result is still expanded (expected - all search results should be collapsed)

同为前端工程师，看到的小bug，不着急。先行感谢:)

**Comment by wanghanzhen** [comment]
Pake只负责打包，与网页逻辑的bug大多数情况下是无关的，可以去https://github.com/book-searcher-org/book-searcher提相关的issue。

**Comment by tw93** [comment]
没事没事 这个是我的一个bro弄的，我明天转给他看看~

**Comment by Cydiar** [comment]
> 没事没事 这个是我的一个bro弄的，我明天转给他看看~
收到，我这边看一下，连上次的名称一起优化一下！
