### ISSUE TITLE
应用无法在电脑上运行

### ISSUE THREAD

**Issue by xp12047** [tw93/Pake#249]
![image](https://user-images.githubusercontent.com/56335408/211505801-55eeb6e1-9e15-4415-810e-8e6e65bc7f2d.png)
我用管理员身份运行的话提示找不到文件  
![image](https://user-images.githubusercontent.com/56335408/211505977-fb4e1a08-12ff-47a6-be9c-5adce1c6e1dd.png)     
但我下载你们制作的程序可以正常运行。我自己生成的两个网页程序都不行呢？我是直接pake+url     
``` 
C:\Program Files\Clash for Windows>pake https://github.com/tw93/Pake
To build the Windows app, you need to install Rust and VS Build Tools.
See more in https://tauri.app/v1/guides/getting-started/prerequisites#installing

√ please input your application name ... pake
You have not provided an app icon, use the default icon.(use --icon option to assign an icon)

up to date, audited 233 packages in 1s

77 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> pake-cli@1.2.1 build
> npm run tauri build --release


> pake-cli@1.2.1 tauri
> tauri build

   Compiling app v0.1.0 (C:\Users\changchneg\AppData\Roaming\npm\node_modules\pake-cli\src-tauri)
    Finished release [optimized] target(s) in 13.32s
        Info Target: x64
     Running candle for "main.wxs"
     Running light to produce C:\Users\changchneg\AppData\Roaming\npm\node_modules\pake-cli\src-tauri\target\release\bundle/msi/pake_1.0.0_x64_en-US.msi
    Finished 1 bundle at:
        C:\Users\changchneg\AppData\Roaming\npm\node_modules\pake-cli\src-tauri\target\release\bundle/msi/pake_1.0.0_x64_en-US.msi

Build success!
You can find the app installer in C:\Program Files\Clash for Windows\pake.msi   
```

电脑是刚重装好的win11专业版。     
打扰了，帮忙看下，谢谢！

**Comment by xp12047** [comment]
> 发现相同的问题。

你的也是这样？

**Comment by xp12047** [comment]
> 两个建议：
> 
> 1. 检查安装环境，要构建 Windows 应用程序，您需要安装 Rust 和 VS 构建工具。[在https://tauri.app/v1/guides/getting-started/prerequisites#installing](https://tauri.app/v1/guides/getting-started/prerequisites#installing)
>    中查看更多信息[](https://tauri.app/v1/guides/getting-started/prerequisites#installing)
> 2. 打包路径别放管理员权限的路径，你在`C:\Program Files\Clash for Windows`打包的，换成它路径，比如c/user/xxx/下载/，或者d盘，下面新建一个xxx文件夹，再去pake

我试着在别的盘新建了文件夹，但是到那个盘之后pake不能用了

**Comment by xp12047** [comment]
> 两个建议：
> 
> 1. 检查安装环境，To build the Windows app, you need to install Rust and VS Build Tools.
>    See more in https://tauri.app/v1/guides/getting-started/prerequisites#installing
> 2. 打包路径别放管理员权限的路径，你是在`C:\Program Files\Clash for Windows`打包的，换成其它路径，比如c/user/xxx/下载/,或者d盘，下面新建一个文件夹，再去执行pake xxx

我在D盘运行cmd执行命令后   
```   
D:\pakebuild>pake https://www.musicenc.com/
To build the Windows app, you need to install Rust and VS Build Tools.
See more in https://tauri.app/v1/guides/getting-started/prerequisites#installing

√ please input your application name ... mus
You have not provided an app icon, use the default icon.(use --icon option to assign an icon)
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\pakebuild/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\pakebuild\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\changchneg\AppData\Local\npm-cache\_logs\2023-01-10T11_05_00_874Z-debug-0.log
file:///C:/Users/changchneg/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:1803
                reject(new Error(`${code}`));
                       ^

Error: 4294963238
    at file:///C:/Users/changchneg/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:1803:24
    at C:\Users\changchneg\AppData\Roaming\npm\node_modules\pake-cli\node_modules\shelljs\src\exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:320:12)

Node.js v18.13.0  
```   
该怎么修改打包路径，帮忙看下。谢谢。给你添麻烦了。

**Comment by xp12047** [comment]
![image](https://user-images.githubusercontent.com/56335408/211536665-19992707-11b7-4e08-87e4-b77980695d4c.png)
vs构建工具好像都有吧？

**Comment by xp12047** [comment]
> ```shell
> npm install -g pake-cli
> ```

重新安装两次都不行还是截图上面的报错。我下载了win10 sdk安装了也不行。不知道什么情况。

**Comment by xp12047** [comment]
我使用c盘user下面的文件夹生成的程序也是无法运行。放在别人的电脑上也是打不开程序的。

**Comment by xp12047** [comment]
> > 我使用c盘user下面的文件夹生成的程序也是无法运行。放在别人的电脑上也是打不开程序的。
> 
> 试试dev分支
> 
> ```shell
> npm uninstall -g pake-cli
> npm install https://github.com/tw93/Pake.git#dev -g
> ```
> 
> 还不行，那就再检查一下nodejs环境，建议重新安装一下nodejs。

谢谢，我试试吧。

**Comment by xp12047** [comment]
> > 我使用c盘user下面的文件夹生成的程序也是无法运行。放在别人的电脑上也是打不开程序的。
> 
> 试试dev分支
> 
> ```shell
> npm uninstall -g pake-cli
> npm install https://github.com/tw93/Pake.git#dev -g
> ```
> 
> 还不行，那就再检查一下nodejs环境，建议重新安装一下nodejs。

node重装了。不行。打包出来的程序依然无法运行。

**Comment by xp12047** [comment]
> > 我在D盘运行cmd执行命令后
> 
> 换powershell试试，cmd有些古老了。

```  
PS D:\pakebuild>
>> pake https://www.musicenc.com/
pake : The term 'pake' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
 spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:1
+ pake https://www.musicenc.com/
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (pake:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException  
```  
还不如cmd。另外我安装了dev那个也不行的报错如下   
```  
up to date, audited 237 packages in 2s

77 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> pake-cli@1.0.1 build
> npm run tauri build --release


> pake-cli@1.0.1 tauri
> tauri build

   Compiling app v0.1.0 (D:\node\node_global\node_modules\pake-cli\src-tauri)
    Finished release [optimized] target(s) in 32.96s
    Finished 0 bundles at:

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, copyfile 'D:\node\node_global\node_modules\pake-cli\src-tauri\target\release\bundle\msi\github_1.0.0_x64_en-US.msi' -> 'D:\pakebuild\github.msi'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: 'D:\\node\\node_global\\node_modules\\pake-cli\\src-tauri\\target\\release\\bundle\\msi\\github_1.0.0_x64_en-US.msi',
  dest: 'D:\\pakebuild\\github.msi'
}

Node.js v18.13.0  
```    
我的问题是用pake打包的程序无法运行。但pake是可以用的。难道是我的电脑系统还没激活的原因嘛。还是我又得重装系统。。

**Comment by xp12047** [comment]
> > > > 
> > > 
> > > 
> > > cmd能用，powershell(非管理员)不能用，说明还是你装的有问题。 多检查一条路径环境吧（用户环境或系统环境全部运行）。 参考环境如下：
> > > ```shell
> > > C:\Users\xxx\AppData\Roaming\local\bin
> > > C:\Users\xxx\.cargo\bin
> > > C:\Users\xxx\AppData\Roaming\npm
> > > C:\Program Files\nodejs\
> > > C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
> > > ```
> > 
> > 
> > 谢谢，除了rust的跟上面路径一样外，其它都不一样。主要是我把node重装在了d盘。但powershell里面倒是可以打开node，npm也可以就是安装的pake包打不开。当时我自己配置的变量。
> 
> 建议安装nodejs时，默认路径，并勾选自动添加path环境。

这个路径下应该是什么`C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\`我的只有10后面的windows performance都没有了

**Comment by xp12047** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > cmd能用，powershell(非管理员)不能用，说明还是你装的有问题。 多检查一条路径环境吧（用户环境或系统环境全部运行）。 参考环境如下：
> > > > > ```shell
> > > > > C:\Users\xxx\AppData\Roaming\local\bin
> > > > > C:\Users\xxx\.cargo\bin
> > > > > C:\Users\xxx\AppData\Roaming\npm
> > > > > C:\Program Files\nodejs\
> > > > > C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
> > > > > ```
> > > > 
> > > > 
> > > > 谢谢，除了rust的跟上面路径一样外，其它都不一样。主要是我把node重装在了d盘。但powershell里面倒是可以打开node，npm也可以就是安装的pake包打不开。当时我自己配置的变量。
> > > 
> > > 
> > > 建议安装nodejs时，默认路径，并勾选自动添加path环境。
> > 
> > 
> > 这个路径下应该是什么`C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\`我的10的文件夹后面的windows performance没有
> 
> 这个是win10 sdk，理论上应该和我路径一样。 建议参考tauri环境安装文档，安装对应的vs 2019 + win10sdk。

我昨天安装了win10 sdk 生成的程序打不开。然后我就卸载了。待会再试试吧。谢谢

**Comment by xp12047** [comment]
![image](https://user-images.githubusercontent.com/56335408/211707618-fcfbd61d-1d7c-4b86-92fd-04fb61d8d498.png)

我的这个电脑一打包cpu就100了。。
下面是我生成的程序。这边依旧无法运行。  
[baidu.zip](https://github.com/tw93/Pake/files/10388509/baidu.zip)

**Comment by xp12047** [comment]
> > ![image](https://user-images.githubusercontent.com/56335408/211707618-fcfbd61d-1d7c-4b86-92fd-04fb61d8d498.png)
> > 我的这个电脑一打包cpu就100了。。 下面是我生成的程序。这边依旧无法运行。 [baidu.zip](https://github.com/tw93/Pake/files/10388509/baidu.zip)
> 
> 尝试手动重新安装rust。

不搞了。安装了win10 SDK 生成的程序依旧能安装但是打不开。折腾两天了。不搞了。搞不好了。

**Comment by xp12047** [comment]
我下载了新版本的powershell使用它来打开pake依旧没用。可以生成也可以安装就是打不开。

**Comment by tw93** [comment]
在线actions打包说不定是一个更好的方法   https://github.com/tw93/Pake/wiki/GitHub-Actions-%E5%9C%A8%E7%BA%BF%E7%BC%96%E8%AF%91%E5%A4%9A%E7%B3%BB%E7%BB%9F%E7%89%88%E6%9C%AC

**Comment by xp12047** [comment]
> > 我下载了新版本的powershell使用它来打开pake依旧没用。可以生成也可以安装就是打不开。
> 
> https://www.rust-lang.org/zh-CN/tools/install 使用rustup-init.exe 64位安装rust。

谢谢。不折腾了。

**Comment by xp12047** [comment]
> 在线actions打包说不定是一个更好的方法 https://github.com/tw93/Pake/wiki/GitHub-Actions-%E5%9C%A8%E7%BA%BF%E7%BC%96%E8%AF%91%E5%A4%9A%E7%B3%BB%E7%BB%9F%E7%89%88%E6%9C%AC

我只是想体验下在电脑上用pake生成的程序。哎，感觉好难啊。谢谢你们。给你们添麻烦了。

**Comment by xp12047** [comment]
> > 我下载了新版本的powershell使用它来打开pake依旧没用。可以生成也可以安装就是打不开。
> 
> https://www.rust-lang.org/zh-CN/tools/install 使用rustup-init.exe 64位安装rust。

一开始安装就是这么安装的。而且我还是看你给别人的留言改了源。用rust也成功安装了别的小工具。

**Comment by xp12047** [comment]
问题解决了。感觉太棒了！！！我昨天偷偷fork了仓库在线编译一个就很兴奋。要知道我踏马就是想体验下编译exe成功内个感受。   
本来我打算放弃了。但是看到在线编译生成的那个程序内心说不出的开心。就是有点慢。我决定在试一次本机编译。这一次总算成功了。原因果真是缺少了微软的一些组件但至于到底什么组件不详。    
[Microsoft Visual C++ Build Tools](https://github.com/throwawaymicrosoft1/Visual-CPP-Build-Tools-OFFLINE-installer)就是这个仓库的安装包我用流量下了四五次！！操！昨晚总算脱下来了。老早就搜到这个东西了。我很喜欢这个老外的思维。    
最后感谢你们，这个项目很牛逼。尽管有PWA。  
分享下我的系统程序截图供参考   
![image](https://user-images.githubusercontent.com/56335408/212523184-02d0845a-2c03-4bcd-b44b-a968f65db4eb.png)
        
@tw93 @Tlntin @c534450673

**Comment by xp12047** [comment]
> > 问题解决了。感觉太棒了！！！我昨天偷偷fork了仓库在线编译一个就很兴奋。要知道我踏马就是想体验下编译exe成功内个感受。 本来我打算放弃了。但是看到在线编译生成的那个程序内心说不出的开心。就是有点慢。我决定在试一次本机编译。这一次总算成功了。原因果真是缺少了微软的一些组件但至于到底什么组件不详。 [Microsoft Visual C++ Build Tools](https://github.com/throwawaymicrosoft1/Visual-CPP-Build-Tools-OFFLINE-installer)就是这个仓库的安装包我用流量下了四五次！！操！昨晚总算脱下来了。老早就搜到这个东西了。我很喜欢这个老外的思维。 最后感谢你们，这个项目很牛逼。尽管有PWA。 分享下我的系统程序截图供参考 ![image](https://user-images.githubusercontent.com/56335408/212523184-02d0845a-2c03-4bcd-b44b-a968f65db4eb.png)
> > @tw93 @Tlntin @c534450673
> 
> 感谢提供的解决办法。 这个组件确实忽略了，因为玩游戏或者一些第三方软件都是顺手就安装了，或者说装完系统就顺便安装了，忽略了它的影响，所以一直没办法复现你的情况。
> 
> 待会我把这个要求也写上去。

😸 不知道是哪个组件？

**Comment by xp12047** [comment]
> > > > 问题解决了。感觉太棒了！！！我昨天偷偷fork了仓库在线编译一个就很兴奋。要知道我踏马就是想体验下编译exe成功内个感受。 本来我打算放弃了。但是看到在线编译生成的那个程序内心说不出的开心。就是有点慢。我决定在试一次本机编译。这一次总算成功了。原因果真是缺少了微软的一些组件但至于到底什么组件不详。 [Microsoft Visual C++ Build Tools](https://github.com/throwawaymicrosoft1/Visual-CPP-Build-Tools-OFFLINE-installer)就是这个仓库的安装包我用流量下了四五次！！操！昨晚总算脱下来了。老早就搜到这个东西了。我很喜欢这个老外的思维。 最后感谢你们，这个项目很牛逼。尽管有PWA。 分享下我的系统程序截图供参考 ![image](https://user-images.githubusercontent.com/56335408/212523184-02d0845a-2c03-4bcd-b44b-a968f65db4eb.png)
> > > > @tw93 @Tlntin @c534450673
> > > 
> > > 
> > > 感谢提供的解决办法。 这个组件确实忽略了，因为玩游戏或者一些第三方软件都是顺手就安装了，或者说装完系统就顺便安装了，忽略了它的影响，所以一直没办法复现你的情况。
> > > 待会我把这个要求也写上去。
> > 
> > 
> > 😸 不知道是哪个组件？
> 
> visual studio build tools这个tauri依赖那里就写了要安装哈。 我认为你可能缺的是miscrosoft visual c++ 2015-2022。

哦，谢谢😊
