### ISSUE TITLE
求支持https://tool.lbbb.cc

### ISSUE THREAD

**Issue by ameizi** [tw93/Pake#25]

**Comment by tw93** [comment]
这个网站的跳转方式有些问题，你能联系上作者直接让他修改一下跳转方式吗，不要用<a href="xxx" target="_blank">xxx</a> 或使用 window.open

**Comment by tw93** [comment]
仔细看了看，这个站点东西有些多了，建议自己fork pake，去实现，不适合放到公共包里面去，关于跳转可以直接 注入js的方式，将所有跳转a标签改一下即可
