### ISSUE TITLE
此应用无法在你的电脑上运行

### ISSUE THREAD

**Issue by xvzhenduo** [tw93/Pake#255]
与 #249 基本相同
我用的是`pake https://github.com/`，安装后运行弹出下面的提示
![image](https://user-images.githubusercontent.com/74353173/211823601-c6bda07b-dcdc-49b8-b9b5-d8f2c9119edb.png)
用命令行运行安装完的程序会弹出如下提示
![image](https://user-images.githubusercontent.com/74353173/211825364-ebe6d97f-180e-499f-b024-9714cae81848.png)
### 环境
Node.js v18.12.1
Windows11 25272.1000
Rust是从[官网](https://www.rust-lang.org/tools/install)下载的最新x64版本
win10 sdk和vs build tool也安装了
### 打包完的安装包
[github.zip](https://github.com/tw93/Pake/files/10393088/github.zip)

**Comment by xp12047** [comment]
问题解决了。请看 #249

**Comment by xp12047** [comment]
> 建议再检查一下环境，特别是vs studio版本，win10 sdk版本是否满足要求。 参考[#253](https://github.com/tw93/Pake/discussions/253) 还不行就用action方案吧。

这个问题貌似不能算Bug了
