### ISSUE TITLE
希望 pake-cli 选项增加简写模式

### ISSUE THREAD

**Issue by aliuq** [tw93/Pake#267]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

比如下面这样，可以减少一些输入

`--width <number>` -> `-w <number>`
`--transparent` -> `-t`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
好建议
