### ISSUE TITLE
[Bug] Could not pack successfully on Apple Silicon CPU

### ISSUE THREAD

**Issue by tim-hub** [tw93/Pake#269]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

1.2.2

### System version

Mac OS 12.6.2

### Node.js version

18.8

### Minimal reproduce step

run `pake https://tauri.app/v1/guides/ --name Tauri-doc --transparent` 

on a Apple Silicon Mac, it seems like lack of some compatible dependency. 

```
error: could not compile `serde` due to 5017 previous errors
       Error failed to build x86_64-apple-darwin binary: failed to build app
```

### What did you expect to see?

generate succesfully

### What did you see instead?

```
error: could not compile `serde` due to 5017 previous errors
       Error failed to build x86_64-apple-darwin binary: failed to build app
```

### Anything else?

nope

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Please take a screenshot for more errors~

**Comment by samwei12** [comment]
same issue here

<img width="418" alt="image" src="https://user-images.githubusercontent.com/12758352/213903325-e4630826-c67d-48a2-8a31-a55e82f8f105.png">


<img width="1120" alt="image" src="https://user-images.githubusercontent.com/12758352/213903374-54bae3ca-ffd7-41aa-8ded-00bc2b7e5f57.png">

**Comment by tw93** [comment]
run `rustup target add x86_64-apple-darwin`

**Comment by samwei12** [comment]
> run `rustup target add x86_64-apple-darwin`

<img width="722" alt="image" src="https://user-images.githubusercontent.com/12758352/214061330-f07ffa08-43a5-43f8-ba86-005722ffe40f.png">

I installed Rust by home brew, no  rustup

**Comment by samwei12** [comment]
After uninstall rust & reinstall from rustup-init, fixed it.
