### ISSUE TITLE
TAURI_SKIP_DEVSERVER_CHECK

### ISSUE THREAD

**Issue by SilverFT** [tw93/Pake#27]
'TAURI_SKIP_DEVSERVER_CHECK' 不是内部或外部命令，也不是可运行的程序
或批处理文件
有遇到过这种情况吗，怎么处理的

**Comment by tw93** [comment]
确定是否安装了node、npm的环境，然后执行npm i、npm run dev 试试

**Comment by SilverFT** [comment]
已经执行了，我发现TAURI_SKIP_DEVSERVER_CHECK这个指令好像用的很少，我去掉就没问题，但是又提示缺少icon，我现在node版本式16.17.1

**Comment by SilverFT** [comment]
配置了，win10专业工作站，之前tauri也有玩过一点，能正常打包的，这次看到这个项目就想试试，TAURI_SKIP_DEVSERVER_CHECK这个关键字就是不识别，很奇怪，我曾经怀疑是不是用法不对，尝试去搜GitHub的代码，整个GitHub就两个项目里面有，一个是tauri库，一个是现在这个项目，找不到，不过既然你们都可以的话，那应该是我电脑环境的问题，我再找找原因好了

**Comment by tw93** [comment]
哦哦 那建议直接干掉，这个是我mac上为了不让他检查目录的一个配置，你直接用tauri的命令即可

**Comment by SilverFT** [comment]
好
