### ISSUE TITLE
[Bug] 在windows上卸载软件非常慢

### ISSUE THREAD

**Issue by fjqz177** [tw93/Pake#271]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

最新版的，用actions构建应用

### System version

windows10

### Node.js version

actions版本

### Minimal reproduce step

安装完该应用后用了不久，然后想卸载，就到安装目录执行了卸载程序，结果卸载的时候停了很久，大约3分钟，十分甚至九分的慢啊（恼），比我卸载iTunes还慢

### What did you expect to see?

请问能否改善，或者出一个exe便携版版本，这样就不用安装了，分享和使用更方便

### What did you see instead?

需要安装卸载，不方便

### Anything else?

希望能出一个全屏的模式，windows上没办法全屏，沉浸感还差一点

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
> 希望能出一个全屏的模式，windows上没办法全屏，沉浸感还差一点

这个突然觉得很有必要一弄

**Comment by fjqz177** [comment]
> 或许可能是你电脑配置较低？建议可以贴一下配置。

Intel(R) Core(TM) i7-8565U CPU
8 GB内存
MX150 GPU
西数SN730 SSD
配置虽然老，但是还是很流畅的，csgo都200帧

希望以后出一个便携版的，不用安装，这样方便很多

**Comment by tw93** [comment]
先关闭，后面支持了放到发布日志里面去
