### ISSUE TITLE
Pake cli on non-https should fail quickly on Mac

### ISSUE THREAD

**Issue by zedongh** [tw93/Pake#295]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

accounding to [pwabuilder](https://docs.pwabuilder.com/#/builder/quick-start) docs

> Your PWA needs to:

> be published at a public URL
> have a complete web manifest
> be secured with HTTPS
> If your app meets these requirements, you can package with PWABuilder.

### Solution

failed quickly if url protocol is `http`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Is it convenient to give a URL that can be reproduced?

**Comment by zedongh** [comment]
> Is it convenient to give a URL that can be reproduced?

`http://yjs.ustc.edu.cn`

pake process is fine, but open app only white screen left.

**Comment by zedongh** [comment]
> > > Is it convenient to give a URL that can be reproduced?
> > 
> > 
> > `http://yjs.ustc.edu.cn`
> > pake process is fine, but open app only white screen left.
> 
> ```shell
> $ pake http://yjs.ustc.edu.cn
> To build the Windows app, you need to install Rust and VS Build Tools.
> See more in https://tauri.app/v1/guides/getting-started/prerequisites#installing
> 
> √ please input your application name ... ustc
> You have not provided an app icon, use the default icon.(use --icon option to assign an icon)
> ```
> 
> In Windows 11, it work ok. ![image](https://user-images.githubusercontent.com/28218658/216527251-8bc27c83-6176-4b1b-a7ad-2bc5e0611e7d.png)

my case is mac os (x86)

**Comment by tw93** [comment]
Refer to the above effect and close first
