### ISSUE TITLE
考虑增加顶部 dom 相关的 css 变量

### ISSUE THREAD

**Issue by AielloChan** [tw93/Pake#30]
避免顶部区域（如左上角的窗口控制）遮挡或干扰网页内容的交互，可以考虑增加如 PWA 所有的一些 CSS 变量，既可以直接兼容 PWA，也能方便开发者进行 UI 适配

https://developer.mozilla.org/en-US/docs/Web/Manifest/display_override#values
https://web.dev/window-controls-overlay/#window-controls-overlay-components

**Comment by tw93** [comment]
好主意 我想想怎么实现 放到下一次版本发布

**Comment by tw93** [comment]
这一块我最后看了看 很取决于当前网站自己的设计，不太能实现，想到了另外一个实现差不多可以解决，先关闭，后面好了就可以使用了
