### ISSUE TITLE
知识星球和得到能支持吗？

### ISSUE THREAD

**Issue by oec2003** [tw93/Pake#32]

**Comment by tw93** [comment]
应该是可以的，你可以fork项目去试试看，比较简单

**Comment by oec2003** [comment]
> 应该是可以的，你可以fork项目去试试看，比较简单 假如不行，可以问问我

试了下，知识星球没啥问题，得到里面点击书籍，是新开一个浏览器 tab 显示的，打包后，点击书籍就没反应了，这个应该怎么处理啊？
