### ISSUE TITLE
[Bug] hread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }'

### ISSUE THREAD

**Issue by chao-eng** [tw93/Pake#323]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

1.2.6
![image](https://user-images.githubusercontent.com/62085978/222366871-5020430c-e2b0-4cf9-99d9-f8f1ba5741c6.png)

### System version

macos 13.0 (22A380)
![image](https://user-images.githubusercontent.com/62085978/222366940-277088e1-e354-4e0b-8942-507e149bf18c.png)

### Node.js version

v16.19.1
![image](https://user-images.githubusercontent.com/62085978/222367028-e20f9ad8-a9f3-4f37-b7f6-346ba31e49c6.png)

### Minimal reproduce step

pake http://www.baidu.com -n baidu

### What did you expect to see?

dmg 安装包

### What did you see instead?

![image](https://user-images.githubusercontent.com/62085978/222367226-12241b10-8ad3-4e41-96d7-549036062ce0.png)

### Anything else?

我看到有类似的问题  通过 升级到node16 pake1.2.1解决， 但是 我再将pake回退回1.2.1时 仍然出现这个问题

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
确定一下 Rust `>=1.63`

**Comment by chao-eng** [comment]
重新安装rust 问题解决了

**Comment by gegewuwuwu** [comment]
rustc -V
rustc 1.68.0 (2c8cc3432 2023-03-06)

重新安装也还是报错
