### ISSUE TITLE
如何更新

### ISSUE THREAD

**Issue by zdrjson** [tw93/Pake#328]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

Mac 下载并且安装了chat gpt dmg包，但是你以后有新版本使用者如何更新？左上角菜单也没有更新选项。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
重新下载覆盖即可
后面慢慢来支持自动更新
