### ISSUE TITLE
那个1.05版本的YouTube.dmg打开之后是programmusic

### ISSUE THREAD

**Issue by detesion** [tw93/Pake#334]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

The YouTube.dmg in 1.05 version is programmusic after opening

### System version

1.05

### Node.js version

none

### Minimal reproduce step

Change the dmg file

### What did you expect to see?

the YouTube.dmg

### What did you see instead?

programmusic.dmg

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
谢谢反馈，我这边重新触发一下打包，稍等会儿就好了

**Comment by likfe** [comment]
参考教程使用 Github Action 打包：https://github.com/likfe/Pake/releases/tag/continuous

Windows 的产物安装后，打开全部都是 programmusic
![20230307180947](https://user-images.githubusercontent.com/7094014/223391629-4cdf3ba3-e92b-420e-b02e-1cc752c0e575.jpg)
