### ISSUE TITLE
导航栏不显示

### ISSUE THREAD

**Issue by wenzilibra** [tw93/Pake#340]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

刚安装完会闪现出导航栏，登录后就不见了
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/98384288/223656439-09cc9acb-b85c-4f0f-a4e5-8e64cca1d066.png">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
正常 我故意干掉的 因为当前上面功能没有太多作用
