### ISSUE TITLE
Feature Request: Automatically fetch the favicons when the `icon` flag is not provided

### ISSUE THREAD

**Issue by pomdtr** [tw93/Pake#347]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

Manually fetching the icon is cumbersome

### Solution

Use this google service (or any equivalent) to fetch the required icon: https://dev.to/derlin/get-favicons-from-any-website-using-a-hidden-google-api-3p1e

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Thank you for your feedback. We have tried this before, but since most websites' favicons are ugly and not very aesthetically pleasing, we have not considered it

**Comment by notBradPitt** [comment]
> Thank you for your feedback. We have tried this before, but since most websites' favicons are ugly and not very aesthetically pleasing, we have not considered it

First of all, thank you for creating this wonderful tool. However, I think this could be made available as an option. I'm facing an issue where it just wouldn't build on Windows with the custom icon I provided it (building for Mac seems to work fine) and it defaults to the breastfeeding emoji icon.

I love this tool, but I'm not sure if this breastfeeding emoji is better and more aesthetically pleasing than most websites' favicons.
