### ISSUE TITLE
打包飞书支持多开

### ISSUE THREAD

**Issue by alili** [tw93/Pake#35]
https://xxx.feishu.cn/messenger

看起来需要指定一下浏览器，不太熟悉tauri怎么配置这个

![image](https://user-images.githubusercontent.com/4102907/197326259-c7090103-6ace-413d-b7ea-9bb862c7d7c5.png)

**Comment by tw93** [comment]
参考此文档，预计需要等到tauri 1.2版本支持，应该快了
因为最新是1.1.1了
