### ISSUE TITLE
Menu "Quit" should be the last one for ux consistency

### ISSUE THREAD

**Issue by westwong0622** [tw93/Pake#356]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

<img width="268" alt="Screenshot 2023-03-16 at 23 40 55" src="https://user-images.githubusercontent.com/32642105/225676400-b6bbbf0c-59c9-46a5-94ae-3c88b593ae80.png">

Should be like this
<img width="218" alt="Screenshot 2023-03-16 at 23 52 54" src="https://user-images.githubusercontent.com/32642105/225676763-676fee3f-79d8-4089-91b1-f395baf3a7f8.png">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Thank you for your suggestion. The latter two seem to come with the system.When Pake reorganizes the menu bar later, it will be adjusted.
