### ISSUE TITLE
[Bug] Can't open URL links from Loop 

### ISSUE THREAD

**Issue by qinip** [tw93/Pake#366]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

1. 从主页上下载的Mac版 Loop.dmg 文件
2. 用Pake 1.3.0 自己打包了一次的Loop

### System version

macOS Ventura 13.2 
(Hackintosh w/ CPU: AMD Ryzen 9 5900HX) 

### Node.js version

npm@9.6.2

### Minimal reproduce step

在侧栏创建新链接，或者在页面中加入URL

### What did you expect to see?

点击链接在默认浏览器中打开页面

### What did you see instead?

点击链接无效

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
谢谢反馈，这个问题下一个版本修复一下，loop的跳转做了一些定制导致，我需要兼容一下

**Comment by tw93** [comment]
已经在 https://github.com/tw93/Pake/releases/tag/V2.0.0-alpha 支持，等待正式版本发布即可，可以关注发布release
