### ISSUE TITLE
支持 magic link 登录的 app

### ISSUE THREAD

**Issue by noyyyy** [tw93/Pake#376]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

有些 app 使用 magic link 登录，而不是用户名密码 or 一次性验证码。没办法在打包后的 app 里主动专跳到某个 URL，实现 magic link 登录。 

一个例子是 https://hoppscotch.io/ ，它使用 firebase 的 magic link，将 token 存到 indexed DB 里面。

### Solution

不太懂怎么解决，也许一个好的办法是上方窗口多一个栏，可以输入 URL 进行转跳。或者在右键菜单里面加入

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
计划加到菜单栏里面去，点击弹出一个输入框，可以直接跳转到对应的地址，等2.0发布后来加

**Comment by tw93** [comment]
已经在 https://github.com/tw93/Pake/releases/tag/V2.0.0-alpha  支持
使用 command+shift+L 可以打开任意URI跳转，回车即可，Command + 左右箭头可以返回下一页
