### ISSUE TITLE
请求支持安全密钥登录方式

### ISSUE THREAD

**Issue by s-leeq** [tw93/Pake#381]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

我目前在需要通过Google登录的应用中无法使用安全密钥登录，请问未来会考虑支持安全密钥的登录方式吗？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
抱歉 暂时应该不会支持，但是2.0版本已经支持谷歌、苹果登录绑定
