### ISSUE TITLE
[Bug] cli show-menu command not exist when running in mac terminal

### ISSUE THREAD

**Issue by leo4512** [tw93/Pake#382]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

commit [0b4cef2](https://github.com/tw93/Pake/commit/0b4cef2a9f9150c962b9aad483131cae7c9d4033)

### System version

MacOS 13.3.1

### Node.js version

node v16.19.1

### Minimal reproduce step

Initiating packaging by adding --show-menu option

### What did you expect to see?

Continue to build the packaging.

### What did you see instead?

pake --help

### Anything else?

In --help, there is no show-menu option as well. 
I hope I can solve this issue by submitting PR, however I am not capable of coding in rust. 
Appreciate your effort for looking into this issue. I have voted a star anyways. 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
As it is still in the testing process, the current stable version has not been switched yet. Please use "npm i pake-cli@2.0.0-alpha -g".
