### ISSUE TITLE
[Bug] 「文心一言」生成的图片无法显示

### ISSUE THREAD

**Issue by sirius60111** [tw93/Pake#386]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

用的 master 分支：6e6018fa15db3de624266de77e24bc703ecafeb8

### System version

macOS Ventura 13.3.1

### Node.js version

v18.15.0

### Minimal reproduce step

1. 打开「文心一言」app（https://yiyan.baidu.com）
2. 让「文心一言」画一幅画，如「画一幅流光溢彩的漂流瓶」
3. 等几秒钟，发现图片加载失败

### What did you expect to see?

图片正常显示

### What did you see instead?

加载失败

### Anything else?

<img width="609" alt="CleanShot 2023-04-13 at 17 49 46@2x" src="https://user-images.githubusercontent.com/7460689/231722606-10038b1a-1968-40b5-9a89-95b473c65064.png">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
我现在没有文心一言的权限，辛苦直接clone pake的仓库，修改掉原来微信读书的地址，然后右键打开调试模式，看看错误在哪儿

**Comment by sirius60111** [comment]
<img width="1443" alt="CleanShot 2023-04-14 at 16 50 08@2x" src="https://user-images.githubusercontent.com/7460689/231994250-4baee0f2-d114-4c65-91ca-10eb6cf2e68d.png">
左边是 github action 打的包，右边是 本地 npm run dev
左边不能显示图片，右边能显示
代码都是一样的，我在前两天 master 的基础上加了 https://github.com/tw93/Pake/commit/74d8935c525768e3ae11096e33cef468fc0e7071 这个 commit

**Comment by tw93** [comment]
哦哦 那还好 等2.0发布好了，现在master已经是2.0了  action里面打包是用的稳定版本，最近我们替换下

**Comment by sirius60111** [comment]
@tw93 文心一言开放注册了，我今天用最新的 Action 打包文心一言，图片还是显示不了 https://github.com/sirius60111/Pake/releases/tag/V2023.9.11
