### ISSUE TITLE
Can you pack it for your cell phone?

### ISSUE THREAD

**Issue by Joackk** [tw93/Pake#401]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

After all, computers are not portable, but mobile phones are usually carried with them, so it will be more convenient if they can be packed into a mobile phone app.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
It is expected that the underlying dependency Tauri will be supported in version 2.0, please wait as the current version does not support it.
