### ISSUE TITLE
建议：Twitter的两个使用不便的地方

### ISSUE THREAD

**Issue by vipzhicheng** [tw93/Pake#402]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

1. 找不到“我的书签”，不知道是什么原因把书签入口给去掉了。
2. Twitter视频无法全屏

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
下一个版本安排
