### ISSUE TITLE
[Bug] Actions编译的windows程序无法关闭

### ISSUE THREAD

**Issue by poctopus** [tw93/Pake#403]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

无

### System version

无

### Node.js version

无

### Minimal reproduce step

无

### What did you expect to see?

无

### What did you see instead?

无

### Anything else?

用Actiions编译出来的Windows程序，点击右上角的关闭，无法正常关闭程序，Alt+F4也无法关闭。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
CLI 已经更新，重新打包应该好了
