### ISSUE TITLE
多站点支持

### ISSUE THREAD

**Issue by txchen** [tw93/Pake#408]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

请问有没有计划支持一个包内含有多个 web app?

场景:
- 多个摸鱼 app 集中到一起, 绑在一个 os app 里方便管理
- app 内支持快捷键, 切换到某一个 web app.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
抱歉，当前 Pake 我的想法是不做大而全的汇集APP的概念，主打简单打包的概念，假如有类似场景，可以自己写一个通用页面，然后再用 Pake 打包试试，或者有更好的想法，欢迎交流~
