### ISSUE TITLE
请问微信读书中正文的字体能否调小一些

### ISSUE THREAD

**Issue by stevenhailin** [tw93/Pake#41]
非常好的应用，赞一个！👍

微信读书中打开一本书，对于正文的文本，默认比浏览器中打开的文本字体要大不少，
能否把默认字体调小一些，或者增加调节字体大小的快捷键呢？

**Comment by tw93** [comment]
command ➕ ➖ 试试

**Comment by stevenhailin** [comment]
> 

第一时间就试了，没反应

**Comment by stevenhailin** [comment]
> 

第一时间就试了，没有反应

**Comment by tw93** [comment]
收到，安排

**Comment by stevenhailin** [comment]
> 感谢反馈，我们安排

辛苦大家了

**Comment by tw93** [comment]
[WeRead_0.2.0_universal.dmg.zip](https://github.com/tw93/Pake/files/9866899/WeRead_0.2.0_universal.dmg.zip)

 @试试这个包，@houhoz 给优化完成了
https://github.com/tw93/Pake/pull/46

**Comment by stevenhailin** [comment]
> 

非常好用，感谢！🙏
