### ISSUE TITLE
Hello, I'm having problems with the version of glibc I'm using. How can I get some older versions of glibc AppImages? > = 2.24

### ISSUE THREAD

**Issue by LTreeshu** [tw93/Pake#411]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

Hello, I'm having problems with the version of glibc I'm using. How can I get some older versions of glibc AppImages? > = 2.24

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LTreeshu** [comment]
deepin 15.9.2发自我的手机-------- 原始邮件 --------发件人： Tlntin ***@***.***>日期： 2023年5月1日周一 11:09收件人： tw93/Pake ***@***.***>抄送： LTreeshu ***@***.***>, Author ***@***.***>主    题： Re: [tw93/Pake] Hello, I'm having problems with the version of glibc I'm using. How can I get some older versions of glibc AppImages? > = 2.24 (Issue #411)
what's your OS and version?

**Comment by LTreeshu** [comment]
👌谢谢发自我的手机-------- 原始邮件 --------发件人： Tlntin ***@***.***>日期： 2023年5月1日周一 18:22收件人： tw93/Pake ***@***.***>抄送： LTreeshu ***@***.***>, Author ***@***.***>主    题： Re: [tw93/Pake] Hello, I'm having problems with the version of glibc I'm using. How can I get some older versions of glibc AppImages? > = 2.24 (Issue #411)


maybe you can try Ubuntu 18.04 to build it with GitHub actions.
now Github actions is based on Ubuntu 20.04

**Comment by tw93** [comment]
Translation: Thank you for your reply. We will take a look at it soon.
@momobobe
