### ISSUE TITLE
[Bug] 回车键逻辑冲突

### ISSUE THREAD

**Issue by hua03** [tw93/Pake#414]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.0.0-alpha7

### System version

macOS 13.1

搜狗输入法

### Node.js version

v16.19.1

### Minimal reproduce step

1. 打包chatgpt网站`pake https://chat.openai.com/auth/login`
2. 登录打包后的网站
3. 使用中文输入prompt, 输入的过程中使用回车，例如中文输入的状态输入`hash`，然后回车，这时候应用会直接把输入的文字直接提交了。

### What did you expect to see?

中文输入状态如果点击回车，应该把输入的字符填到输入框中

### What did you see instead?

中文输入状态如果点击回车，输入的字符会被直接提交

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
的确有问题  谢谢反馈 我修复一下

**Comment by tw93** [comment]
看起来应该是 Safari 本身的一个bug，暂时不太好修复，可以试试Safari浏览器是不是有这个相同的bug
后面我这边有办法hack的话 就直接更新即可

**Comment by tw93** [comment]
终于修复了，今天发布一个版本

**Comment by LidamaoHub** [comment]
目前使用2.3.1版本,仍然复现问题,mac环境
打包https://claude.ai/chat后使用搜狗中文输入法是输入node并回车,本意是输入"node"这个英文字符,但是直接触发为"发出"

**Comment by houzixiashanxiedaima** [comment]
这个问题，似乎在最新的版本中又出现了，使用的是 README 中提供的 Grok；
操作系统是：macOS 15.6
输入法是系统自带的输入法
