### ISSUE TITLE
打包失败[Bug] 

### ISSUE THREAD

**Issue by Yunkou** [tw93/Pake#416]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

pake-cli@2.0.2

### System version

- macOS 13.3.1 (22E261)
- Apple M1 Max

### Node.js version

-  node v16.14.0
-  npm 8.3.1

### Minimal reproduce step

-  pake https://xxx  --name xxx

### What did you expect to see?

-

### What did you see instead?

> pake-cli@2.0.2 build
> npm run tauri build --release

> pake-cli@2.0.2 tauri
> tauri "build"

 Downloading crates ...
  Downloaded malloc_buf v0.0.6
error: failed to verify the checksum of `malloc_buf v0.0.6`
       Error failed to build app: failed to build app
file:///xxx/.bun/install/global/node_modules/pake-cli/dist/cli.js:2021
                reject(new Error(`${code}`));

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
科学上网试试，看起来是下载时候出错了，重新试试

**Comment by icelo0** [comment]
@tw93 我升级到2.0.5打包报错，报错如下：
     Running bundle_dmg.sh
       Error failed to bundle project: error running bundle_dmg.sh
file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:2023
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:2023:24
    at /usr/local/lib/node_modules/pake-cli/node_modules/shelljs/src/exec.js:145:9
    at ChildProcess.exithandler (node:child_process:420:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)

Node.js v18.10.0

**Comment by Aierie** [comment]
On M2 Macbook - when I use the `--transparent` flag, `bundle_dmg.sh` errors. Otherwise it works.
