### ISSUE TITLE
[Bug] Poe包 Linux安装后名字为Peo

### ISSUE THREAD

**Issue by ljz2021** [tw93/Pake#417]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.0

### System version

Ubuntu 20.04

### Node.js version

10.19.0

### Minimal reproduce step

Install the deb package and then discover a naming error.

### What did you expect to see?

fix it

### What did you see instead?

nope

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
https://github.com/tw93/Pake/releases/download/V2.0.0/Poe_x86_64.deb
辛苦直接下载这个最新的 已经修复
