### ISSUE TITLE
[Bug] window.prompt API used in the website, after packaging, it did not pop up normally

### ISSUE THREAD

**Issue by cy920820** [tw93/Pake#421]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.0.4

### System version

MacOS 13.3.1

### Node.js version

v16.15.1

### Minimal reproduce step

pake https://chat.0x403.com --name ChatGPT --transparent

### What did you expect to see?

Click on the function button on the website, and the prompt output pop-up window will pop up normally

### What did you see instead?

Clicking did not pop up a prompt pop-up window

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
https://github.com/tauri-apps/tauri/issues/4783

**Comment by tw93** [comment]
I see that the original website has been modified to use a custom prompt. In addition, this feature is not yet fully developed in Tauri. We will wait for it to be improved before supporting it and include it in our plan, including alert and confirm.
