### ISSUE TITLE
打开新标签页的话点击没有反应，能不能打开默认的浏览器？

### ISSUE THREAD

**Issue by lazy-ape** [tw93/Pake#432]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

2.0.4

### Solution

如果链接是打开新标签页点击没有反应

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhangweimtan** [comment]
happened on 2.0.0 upper, any links on the app webpage just cannot click to open, only tried by right click opening links on the other window. don't know why, anyway pake-cli@1.3.1 works fine.

**Comment by tw93** [comment]
Is this a new tab page opened using window.open? @zhangweimtan @lazy-ape

**Comment by tw93** [comment]
pake-cli@2.0.6

**Comment by lazy-ape** [comment]
@tw93  你好，我用了最新版本 2.1.12 打包的软件打开新标签页的链接依然打不开的。网页用的 vue，链接的打开方法是 `window.open(url, '_blank')` ， 电脑系统 win10, node 版本 v18.16.1

**Comment by tw93** [comment]
方便给一下页面吗 我空我本地调试一下

**Comment by lazy-ape** [comment]
这个是我们内部系统的页面，不太方便提供，不过我可以新建一个 vue 项目试一下，打包的时候是不是需要指定什么参数？我只指定了 name，正常的话是新打开一个窗口还是打开默认的浏览器呢？
