### ISSUE TITLE
[Bug] 某些链接被识别为了下载文件，无法跳转

### ISSUE THREAD

**Issue by AndySze** [tw93/Pake#434]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.0.4

### System version

Mac OS

### Node.js version

v19.8.1

### Minimal reproduce step

打包Conflunce Wiki系统，此Wiki中的很多链接都是以 https://xxxxxx.action 结尾的，被识别为了下载文件，导致链接无法跳转

### What did you expect to see?

正常跳转链接

### What did you see instead?

下载了一个文件

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
最近版本我们修复一下，Conflunce Wiki系统 这个系统有办法截图给我看看所有的跳转地址吗？

**Comment by AndySze** [comment]
是要看链接的形式吗？还是要看什么？  
老版本是可以的，应该是1.xx具体忘了哪个版本了

以下截图里的3个链接都被识别为了下载文件：
<img width="455" alt="image" src="https://github.com/tw93/Pake/assets/2310069/9cae399b-d1e0-42d5-a3d9-80132ed41ada">

**Comment by tw93** [comment]
你直接给对应的地址形式，url 即可

**Comment by AndySze** [comment]
这个几个地址分别是：
People: https://wiki.xxx.com/browsepeople.action
Manage Space Blueprints: https://wiki.xxx.com/blueprintcreator/space-blueprints/space-blueprints-management.action
Create: https://wiki.xxx.com/pages/createpage.action?spaceKey=MP&fromPageId=64815211&src=quick-create

**Comment by tw93** [comment]
https://github.com/?spaceKey=MP&fromPageId=64815211&src=quick-create

**Comment by tw93** [comment]
pake-cli@2.0.6
