### ISSUE TITLE
[Bug]  npm ERR! Cannot set properties of null (setting 'peer')

### ISSUE THREAD

**Issue by coola007** [tw93/Pake#436]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

master

### System version

darwin 22.4.0

### Node.js version

20.1

### Minimal reproduce step

pake https://www.baidu.com --name baidu --transparent

### What did you expect to see?

mac 环境编辑 出错:
5581 verbose stack TypeError: Cannot set properties of null (setting 'peer')
5581 verbose stack     at visit (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:104:54)
5581 verbose stack     at visitNode (/usr/local/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:58:25)
5581 verbose stack     at next (/usr/local/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:44:19)
5581 verbose stack     at depth (/usr/local/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:83:10)
5581 verbose stack     at depth (/usr/local/lib/node_modules/npm/node_modules/treeverse/lib/depth.js:27:12)
5581 verbose stack     at unsetFlag (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:99:5)
5581 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:65:7
5581 verbose stack     at Map.forEach (<anonymous>)
5581 verbose stack     at calcDepFlagsStep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:41:17)
5581 verbose stack     at visit (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:12:20)
5582 verbose cwd /usr/local/lib/node_modules/pake-cli
5583 verbose Darwin 22.4.0
5584 verbose node v20.1.0
5585 verbose npm  v9.6.4
5586 error Cannot set properties of null (setting 'peer')
5587 verbose exit 1
5588 timing npm Completed in 68344ms

### What did you see instead?

npm ERR! Cannot set properties of null (setting 'peer')

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by coola007** [comment]
尝试删除node_module 还是不行

**Comment by coola007** [comment]
是macOs呀

**Comment by coola007** [comment]
intel的, 
![image](https://github.com/tw93/Pake/assets/6283842/2c0e57bf-3b76-495c-b0a3-33b675b8dfaf)

另一个情况:
在win11的电脑编译, 然后放到另一台 没有全新系统的win7电脑 显示无法打开此安装程序包
![image](https://github.com/tw93/Pake/assets/6283842/311abb87-9155-4a4c-832e-008ab53a7513)

**Comment by tw93** [comment]
我用相同的环境试了试，没有问题，mac 这里可以试试将 pake-cli  文件删除以后，重新安装试试
