### ISSUE TITLE
[Bug] 下载的文件找不到

### ISSUE THREAD

**Issue by jaysoncho92** [tw93/Pake#437]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

pake --version
2.0.4

### System version

macOS 13.3.1 (22E261)

### Node.js version

node -v
v18.12.1

### Minimal reproduce step

pake https://zbook.lol/ --name zbook  --transparent
用以上命令打包app，打开app后搜索一本电子书，点击下载，下载完成后找不到下载的文件。

### What did you expect to see?

下载文件所在目录

### What did you see instead?

文件下载完成

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
去下载目录看看，或者看看有没有toast提示

**Comment by jaysoncho92** [comment]
> 

正常在网页https://zbook.lol/ -中下载默认是保存到用户下载目录，找过了没有，也没有看到其它提示。

**Comment by lakca** [comment]
应该是报错了吧，[download_rs](https://docs.rs/crate/download_rs/latest/source/src/sync_download.rs)这个库有些问题，这里`content_length().unwrap()`可能会报错，看了一下这个库貌似被废弃了，建议替换一下。
![image](https://github.com/tw93/Pake/assets/16255922/b45b556b-3a9e-4dd4-a8f9-e68f6d6cfe56)

**Comment by tw93** [comment]
谢谢反馈，明天我统一都看一下

**Comment by tw93** [comment]
看了看是下载这边还不支持 blob 的类型，即使干掉 total_size 貌似也作用不大，最后会走到 error 里面去，只能先等等了，暂时这个先修复不了 
@lakca @jaysoncho92  有好法子欢迎直接PR
