### ISSUE TITLE
[Bug] CMD+W Minimizes Window Instead of Closing

### ISSUE THREAD

**Issue by singularitti** [tw93/Pake#438]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.0.0

### System version

macOS 13.3

### Node.js version

inapplicable

### Minimal reproduce step

- Open any window in the Pake-produced app (such as ChatGPT.app).
- Press CMD+W.

### What did you expect to see?

I expected the active window to close, as is the standard behavior with the CMD+W shortcut in macOS.

### What did you see instead?

The active window did not close as expected. Instead, it was minimized, which is the behavior typically associated with the CMD+M shortcut in macOS. This seems to be a bug causing an overlap in the functionality of these two shortcuts.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by singularitti** [comment]
This also happens when I click the "x" icon on the window.

**Comment by KevinYouu** [comment]
The same problem

**Comment by AprilNEA** [comment]
一样的问题

**Comment by tw93** [comment]
😂 Sorry, this is actually intentional on my part. Because most of the scenarios for pake packaging are tools that require quick use, you can use command + q to close it here. You can try this habit with applications such as Telegram, various command line tools, and music software.

**Comment by ooopscc** [comment]
When using Youtube Music, it should be able to run in the background even when the window is closed. Currently, it occupies a spot on the Dock without any practical purpose.

Paked app should adhere to the design guidelines of macOS too, Command+W is reserved as close window not minimize.

**Comment by RooobinYe** [comment]
Can I request to reopen this issue? Can an option be added to control whether to close or minimize the window?
