### ISSUE TITLE
fork 之后，actions编译报错  [Bug] 

### ISSUE THREAD

**Issue by buildnewapp** [tw93/Pake#440]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

最新

### System version

mac

### Node.js version

最新

### Minimal reproduce step

1 fork pake
2 actions , Build App with Cache #1
   Error 403: Resource not accessible by integration
   https://github.com/buildnewapp/Pake/actions/runs/4998229341
3 action , Build App with Pake Cli #1
   [windows-latest] No files were found with the provided path: node_modules/pake-cli/output/*. No artifacts will be uploaded.
   https://github.com/buildnewapp/Pake/actions/runs/4978013243

### What did you expect to see?

正常输出打包

### What did you see instead?

https://github.com/buildnewapp/Pake/actions/runs/4998229341
https://github.com/buildnewapp/Pake/actions/runs/4978013243

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by sunbigfly** [comment]
I have the same BUG

**Comment by sunbigfly** [comment]
> 显然是没有权限导致的，请再看看 wiki,给予 actions 权限，目测是缺了第二步。显然是没有权限导致的，请再看看 wiki,给予 actions 权限，目测是缺了第二步。显然是没有权限导致的，请再看看 wiki,给予 actions 权限，目测是缺了第二步。 [链接链接链接](https://github.com/tw93/Pake/wiki/%E5%9C%A8%E7%BA%BF%E7%BC%96%E8%AF%91%EF%BC%88%E5%BC%80%E5%8F%91%E8%80%85%E4%BD%BF%E7%94%A8%EF%BC%89#2%E5%89%8D%E5%BE%80-actions-%E9%A1%B5%E9%9D%A2%E5%90%AF%E7%94%A8-github-actions)

It works now, thank you.
