### ISSUE TITLE
[Bug]  Error failed to bundle project: `Io Error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer`

### ISSUE THREAD

**Issue by lcawen** [tw93/Pake#442]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

pake-cli@2.0.5

### System version

window 11

### Node.js version

16.19.1

### Minimal reproduce step

pake https://www.baidu.com/ --name baidu --transparent

### What did you expect to see?

create baidu.exe for window

### What did you see instead?

up to date in 644ms

68 packages are looking for funding
  run `npm fund` for details

> pake-cli@2.0.5 build
> npm run tauri build --release

> pake-cli@2.0.5 tauri
> tauri build

   Compiling app v0.1.0 (C:\Users\nxin\AppData\Roaming\npm\node_modules\pake-cli\src-tauri)
    Finished release [optimized] target(s) in 22.24s
warning: the following packages contain code that will be rejected by a future version of Rust: winapi v0.2.8
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 6`
        Info Verifying wix package
 Downloading https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
        Warn Sending fatal alert BadCertificate
       Error failed to bundle project: `Io Error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer`
file:///C:/Users/nxin/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:2023
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///C:/Users/nxin/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:2023:24
    at C:\Users\nxin\AppData\Roaming\npm\node_modules\pake-cli\node_modules\shelljs\src\exec.js:145:9
    at ChildProcess.exithandler (node:child_process:410:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by HogwartsRow** [comment]
同样遇到了此问题，不过系统是 macOS, 安装的时候使用了 sudo 方式不知道是否有个原因

**Comment by lcawen** [comment]
> 网络问题，看起来你需要和谐上网。

上墙了，还是同样的错

**Comment by lcawen** [comment]
> > > 网络问题，看起来你需要和谐上网。
> > 
> > 
> > 上墙了，还是同样的错
> 
> 那就升级nodejs版本试试。

不是node版本的问题，进入到xxx/PAKE-CLI/src-tauri目录，使用cargo run，是可以正常运行起来一个桌面端的baidu的，但是使用pake命令运行不可以
![image](https://github.com/tw93/Pake/assets/4370695/b7b3b63b-9ef2-4c31-912f-61dadab77359)

**Comment by HogwartsRow** [comment]
> > > > 网络问题，看起来你需要和谐上网。
> > > 
> > > 
> > > 上墙了，还是同样的错
> > 
> > 
> > 那就升级nodejs版本试试。
> 
> 不是node版本的问题，进入到xxx/PAKE-CLI/src-tauri目录，使用cargo run，是可以正常运行起来一个桌面端的baidu的，但是使用pake命令运行不可以 ![image](https://user-images.githubusercontent.com/4370695/239474929-b7b3b63b-9ef2-4c31-912f-61dadab77359.png)

Rust、Node 版本都符合要求也不行，试了不用 sudo 的方式安装了pake-cli也不行

**Comment by tw93** [comment]
@HogwartsRow @lcawen 不需要使用sudo，可以是谁将 node_module 里面的 pake-cli 彻底删除，然后重新安装。

**Comment by SuZher** [comment]
网络问题，我这边跟你的问题一样，过一晚上就好了。
