### ISSUE TITLE
[Bug] The inner content section displays blank margin when zoom out

### ISSUE THREAD

**Issue by teeerrytan** [tw93/Pake#443]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.0

### System version

MacOS Ventura 13.4

### Node.js version

v19.5.0

### Minimal reproduce step

To zoom out the content, press the `command` and `-` keys. Once you do this, a blank margin will appear around the content, as shown in the screenshot below.<img width="1377" alt="image" src="https://github.com/tw93/Pake/assets/10609214/ca53f404-c142-4db5-8aa7-9094231ec69f">

### What did you expect to see?

To ensure a seamless display, the size of the outer window should be adjusted to fit the content section without any blank spaces.

### What did you see instead?

There is a blank margin surrounding the inner section.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
This is a problem with POE itself. You can try command + 0 to restore, or command + + to enlarge.
