### ISSUE TITLE
[Bug] 更新到 Pake 2.0 后，将文件拖拽到应用程序窗口中无反应

### ISSUE THREAD

**Issue by WitherZuo** [tw93/Pake#444]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

Pake 2.0.4

### System version

Windows 11 Insider Preview 25357.1 (Canary)

### Node.js version

v18.12.1

### Minimal reproduce step

1、安装并打开一个 Pake 应用，例如这个：[点击此处](https://github.com/WitherZuo/photopea-webapp) 以及 [点击此处](https://github.com/WitherZuo/baimiao-webapp)  
2、将文件拖拽到应用窗口里，鼠标指针变成拖拽图标，但是拖拽后松开没有任何反应

### What did you expect to see?

拖拽文件到应用窗口后可以有反应（例如：打开并加载指定文件）

### What did you see instead?

鼠标指针变成拖拽指示器，松开后应用窗口没有任何反应

### Anything else?

之前用 Pake 1.x 打包过，当时是正常的，直接打包完成后就可以使用拖拽功能，不需要做任何代码层面的改动。但是从 Pake 2.0 开始就出现这个问题了。我看到 Pake 2.x 的更新日志里有说渲染端从 WRY 换成 Tauri 自带的，是否和这条更新日志有关？🤣（我没有保留使用 Pake 1.x 打包的项目，所以只能这样了）  

https://github.com/tw93/Pake/assets/25317916/18d73f43-0175-4b87-896f-8555dbdfc262

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by WitherZuo** [comment]
UPDATE：根据 Tauri 官方的 API 文档，我做了一个简短的测试：

1. 修改 `src-tauri/pake.json` 文件，在 `windows` 字段下添加 `"fileDropEnabled": false` 配置项：
```json
"windows": [
    {
      "url": "https://ps.gaoding.com/#/",
      "transparent": true,
      "fullscreen": false,
      "width": 1200,
      "height": 780,
      "resizable": true,
      "fileDropEnabled": false,
      "url_type": "web"
    }
  ],
```

2. 保存后重新编译构建应用，然后把文件拖入打开的应用窗口，**无任何反应**
3. 接下来再修改 `tauri.conf.json` 文件，在 `tauri` 字段下新增 `windows` 字段，然后添加 `"fileDropEnabled": false` 配置项：
```json
{
  ...
  "tauri": {
    "windows": [
      {
        "fileDropEnabled": false
      }
    ],
  ...
}
```
4. 保存后再次重新编译构建应用，此时会打开两个窗口，其中一个为窗口标题 `Tauri App` 的窗口，另一个是 Pake 应用窗口，然后把文件分别拖入到这两个窗口中，**`Tauri App` 标题的窗口能够正常响应文件拖拽事件，而 Pake 应用窗口仍然无效**。

**Comment by tw93** [comment]
修复了，辛苦直接等最近几天的新办法发布，这个属性理解有些坑了 disable_file_drop_handler，这样调用下居然可以了

**Comment by tw93** [comment]
pake-cli@2.0.6
