### ISSUE TITLE
装了这个，才知道失去了各种插件的打包网页这么难用

### ISSUE THREAD

**Issue by zhl111** [tw93/Pake#445]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

不时蹦出的广告提醒我这才是常态。。。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Yangli93** [comment]
如果能把浏览器插件打包进去就好了

**Comment by tw93** [comment]
抱歉 现在不支持chrome插件的能力，看起来以后应该也很难支持，其实假如网站广告过多，是不是这个网站本身就不太值得被打包呢😂
