### ISSUE TITLE
[Bug] Can't download file in client

### ISSUE THREAD

**Issue by AielloChan** [tw93/Pake#447]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.0.5

### System version

13.4 (22F66)

### Node.js version

v16.20.0

### Minimal reproduce step

```bash
pake https://figma.com --name 'figma' --icon ~/Downloads/figma.icns --transparent
```

make a figma app, and draw some graph, then export it, no response

<img width="616" alt="image" src="https://github.com/tw93/Pake/assets/7900765/7cff3c07-858c-402b-a611-d4d0f0fa31e9">

### What did you expect to see?

like in web, will download this exported file.

### What did you see instead?

no any response

### Anything else?

no

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
I took a look at the special way of downloading exported files from Figma, but currently I tried and couldn't capture this event being passed out, so it's not easy to support.

**Comment by tw93** [comment]
看起啦 @jeasonnow 已经修复，我们最简发布一个版本
