### ISSUE TITLE
可否支持非管理员安装呢？

### ISSUE THREAD

**Issue by ZarkMedo** [tw93/Pake#460]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

公司电脑管理员权限被回收了，只能为当前用户安装

### Solution

是否可以提供仅为本机安装，或者绿色免安装版，谢谢啦

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
试试这个  http://www.its365.net/bbs/showtopic-46.aspx 教程‘
此外 Pake 当前不太好支持 非管理安装的配置，因为当前还有很多需求排着在做，不过假如你有法子，很欢迎提交PR

**Comment by IzualYang** [comment]
用msiexec的管理安装模式解压缩就行了吧
