### ISSUE TITLE
可以解除 Poe for Mac 的复制限制？谢谢！

### ISSUE THREAD

**Issue by indincys** [tw93/Pake#471]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

你好，我在使用 Pake 打包的 Poe.app时，偶尔会出现无法复制内容的情况。以下是正常情况时的复制效果：

![CleanShot 2023-06-18 at 10 16 27@2x](https://github.com/tw93/Pake/assets/14246072/f4794b54-a05d-4ecf-a311-bd7b1bc094b6)

但偶尔也会出现 Poe.app 鼠标无法选词，只能右键全部复制的情况，如图：

![CleanShot 2023-06-18 at 10 19 32@2x](https://github.com/tw93/Pake/assets/14246072/ca38362a-f502-4552-ba9f-fa1820812302)

。猜测可能是 Poe 有自己的复制限制，想问下复制限制这个可以解除吗？谢谢！

### Solution

无

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
试了试 其实你完全可以 Command + C 来复制就好啦

**Comment by indincys** [comment]
Command + C有时也复制不了，不清楚是不是我这边的问题，感谢答复！
