### ISSUE TITLE
[Bug] 打包imagestool无法下载图片到本地

### ISSUE THREAD

**Issue by abcmiao** [tw93/Pake#477]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

最新版本

### System version

macOS 13.4

### Node.js version

18.16.0

### Minimal reproduce step

pake https://imagestool.com/zh_CN/ --name ImagesTool --transparent
直接跑，生成的app，打开后导入图片，比如图片压缩，压缩完之后，点击下载图片或者下载按钮，没反应
试了可以上传

### What did you expect to see?

希望可以可以直接下载图片，或者文件

之前为另一款相似功能的软件付过费：fluid，打包好的app也是无法下载图片。现在看来pake就能完美实现网页打包app，还免费

### What did you see instead?

啥也没看到

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
![image](https://github.com/tw93/Pake/assets/16950207/842945c9-2b2d-4547-92fb-100d1da6b675)
这个网站的操作很骚，有防 debugger 模式而且其触发下载不是常用的 a.click 的形式，可能需要进行一些针对性的处理。

**Comment by jeasonnow** [comment]
https://github.com/tw93/Pake/pull/478
这个可以 fix 这个问题，之前默认所有的下载都是使用 a.click 的形式，现在调整为拦截创建 a 标签的同时，监听 a 标签的点击事件。

**Comment by jeasonnow** [comment]
[ImagesTool.dmg.zip](https://github.com/tw93/Pake/files/11817063/ImagesTool.dmg.zip)
试试这个，使用最新代码打出来的包，我测试应该是没问题了。
@abcmiao

**Comment by abcmiao** [comment]
> [ImagesTool.dmg.zip](https://github.com/tw93/Pake/files/11817063/ImagesTool.dmg.zip) 试试这个，使用最新代码打出来的包，我测试应该是没问题了。 @abcmiao

感谢大佬，测试可以了。用最新代码打包就可以了对吧，我去重新搞下整个图标，感谢感谢
