### ISSUE TITLE
请问如何清除缓存呢（如果有）？

### ISSUE THREAD

**Issue by RoyRao2333** [tw93/Pake#48]
你好，请问一下Pake打包的App，如果产生了缓存文件，应该在哪里去清理呢？

**Comment by tw93** [comment]
主要是什么场景哦
试试通用清理工具 或者删掉重装

**Comment by RoyRao2333** [comment]
> 主要是什么场景哦 试试通用清理工具 或者删掉重装

考虑到web app可能会有media文件缓存或者cookie等，提供一个清理入口可能会好点😂

**Comment by tw93** [comment]
我们调研调研 谢谢反馈

**Comment by RoyRao2333** [comment]
> 我们调研调研 谢谢反馈

非常感谢☺️

**Comment by tw93** [comment]
看了看没有太好办法，不过这个东西按理没有什么缓存，假如有到时候辛苦提供一下case给我们哦，这样应该会有办法去解决，这个问题我先关闭了哦，谢谢反馈～

**Comment by RoyRao2333** [comment]
> 看了看没有太好办法，不过这个东西按理没有什么缓存，假如有到时候辛苦提供一下case给我们哦，这样应该会有办法去解决，这个问题我先关闭了哦，谢谢反馈～

我刚才看了看，发现打包出来的App的缓存在~/Library/Caches里，这个估计要用户手动来了，或者看看tauri有没有相应的command来clean cache（之前搜了搜，没找到😂）

**Comment by tw93** [comment]
嗯嗯 而且普通清理工具其实应该也行，更像是客户端一般不会提供这个功能

**Comment by Novices666** [comment]
我也有这个问题，我ssl证书关掉了（不使用https了），但是重新打包http的地址后，会提示
你的连接不是专用连接
攻击者可能试图从 *网址* 窃取你的信息(例如，密码、消息或信用卡)。
NET::ERR_CERT_AUTHORITY_INVALID

在浏览器的话，直接清除缓存就好，但是咱们这个我一直没找到缓存目录或者ssl证书删除入口

**Comment by puzzle9** [comment]
@Novices666  这个 是有缓存目录的
我这里测试是1天左右缓存会失效
此刻 我并没有找到win的缓存目录位置

**Comment by Yousa-Mirage** [comment]
win的缓存应该是%AppData%\{应用名如Gemini}中的EBWebView文件夹，删除后应用恢复默认状态
