### ISSUE TITLE
OpenAI 新增对GPT4-Mobile模型限制

### ISSUE THREAD

**Issue by linkedlist771** [tw93/Pake#481]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

`2023-6-23` openai 新增对`GPT4-Mobile`模型限制，已将其归类到25/3小时的限制中。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
看起来是被更新了 那就没有办法了，这个也解决不了，先关闭好了
