### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by hzmings** [tw93/Pake#493]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

✼ No icon given, default in use. For a custom icon, use --icon option.
✸ Installing package...

up to date, audited 224 packages in 3s

68 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

✔ Package installed!
✺ Building app...

> pake-cli@2.1.12 build
> npm run tauri build --release

> pake-cli@2.1.12 tauri
> tauri build

   Compiling app v0.1.0 (D:\helloworld\Node\node-v18.16.1-win-x64\node_modules\pake-cli\src-tauri)
error: failed to run custom build command for `app v0.1.0 (D:\helloworld\Node\node-v18.16.1-win-x64\node_modules\pake-cli\src-tauri)`

Caused by:
  process didn't exit successfully: `D:\helloworld\Node\node-v18.16.1-win-x64\node_modules\pake-cli\src-tauri\target\release\build\app-95d9a87d776b86a7\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rerun-if-changed=png\weekly_256.ico
  package.metadata does not exist

  --- stderr
  thread 'main' panicked at 'Couldn't to execute windres to compile "D:\helloworld\Node\node-v18.16.1-win-x64\node_modules\pake-cli\src-tauri\target\release\build\app-55ddf6e071a07994\out\resource.rc" into "D:\helloworld\Node\node-v18.16.1-win-x64\node_modules\pake-cli\src-tauri\target\release\build\app-55ddf6e071a07994\out/libresource.a": program not found', C:\Users\pamica\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\embed-resource-2.1.1\src\windows_not_msvc.rs:47:23
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       Error failed to build app: failed to build app
file:///D:/helloworld/Node/node-v18.16.1-win-x64/node_modules/pake-cli/dist/cli.js:369
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///D:/helloworld/Node/node-v18.16.1-win-x64/node_modules/pake-cli/dist/cli.js:369:24
    at D:\helloworld\Node\node-v18.16.1-win-x64\node_modules\pake-cli\node_modules\shelljs\src\exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

### System version

win10

### Node.js version

18

### Minimal reproduce step

1

### What did you expect to see?

1

### What did you see instead?

1

### Anything else?

2

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tw93** [comment]
有按照这个配置吗 https://github.com/tw93/Pake/blob/master/bin/README_CN.md#windowslinux-%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by tw93** [comment]
打包错误 合并到这个 https://github.com/tw93/Pake/issues/497
