### ISSUE TITLE
Window jump/窗口跳转

### ISSUE THREAD

**Issue by Grey-Wind** [tw93/Pake#495]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

Whether internal jump Windows can be supported
Because some pages need to jump
是否可以支持内部跳转窗口
因为有的网页需要跳转

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
有没有具体页面的案例，我看看

**Comment by tw93** [comment]
一周没有回复，暂时关闭，假如看到了，辛苦给我一下信息，同时可以打开这个issue
