### ISSUE TITLE
[Bug]  Connection Failed: tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer`

### ISSUE THREAD

**Issue by TheCaptainUniverse** [tw93/Pake#496]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

v2.0.6

### System version

win11

### Node.js version

v18.16.0

### Minimal reproduce step

https://xxx.xxx --name Blog

### What did you expect to see?

Build success

### What did you see instead?

Compiling app v0.1.0 (C:\Users\25853\AppData\Roaming\npm\node_modules\pake-cli\src-tauri)
    Finished release [optimized] target(s) in 22.44s
        Info Verifying wix package
 Downloading https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
        Warn Sending fatal alert BadCertificate
       Error failed to bundle project: `https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip: Connection Failed: tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer`
file:///C:/Users/25853/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:370
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///C:/Users/25853/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:370:24
    at C:\Users\25853\AppData\Roaming\npm\node_modules\pake-cli\node_modules\shelljs\src\exec.js:145:9
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
有按照这个配置吗？https://github.com/tw93/Pake/blob/master/bin/README_CN.md#windowslinux-%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by tw93** [comment]
合并到这个 https://github.com/tw93/Pake/issues/497
