### ISSUE TITLE
[Bug]  pake fail

### ISSUE THREAD

**Issue by 2574021892** [tw93/Pake#497]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.1.2

Downloaded windows v0.39.0 (registry `rsproxy`)
   Compiling proc-macro2 v1.0.60
   Compiling unicode-ident v1.0.9
   Compiling quote v1.0.28
   Compiling autocfg v1.1.0
   Compiling serde v1.0.164
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.109
   Compiling memchr v2.5.0
   Compiling windows_x86_64_msvc v0.48.0
   Compiling ppv-lite86 v0.2.17
   Compiling siphasher v0.3.10
   Compiling winapi v0.3.9
   Compiling getrandom v0.1.16
   Compiling log v0.4.19
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling getrandom v0.2.10
   Compiling parking_lot_core v0.9.8
   Compiling fnv v1.0.7
error: linker `link.exe` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.

note: VS Code is a different product, and is not sufficient.

error: could not compile `windows_x86_64_msvc` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `quote` due to previous error
error: could not compile `getrandom` due to previous error
error: could not compile `proc-macro-hack` due to previous error
error: could not compile `memchr` due to previous error
error: could not compile `serde` due to previous error
error: could not compile `proc-macro2` due to previous error
error: could not compile `syn` due to previous error
error: could not compile `parking_lot_core` due to previous error
error: could not compile `winapi` due to previous error
       Error failed to build app: failed to build app
file:///D:/dev/nvm/v16.19.1/node_modules/pake-cli/dist/cli.js:369
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///D:/dev/nvm/v16.19.1/node_modules/pake-cli/dist/cli.js:369:24
    at D:\dev\nvm\v16.19.1\node_modules\pake-cli\node_modules\shelljs\src\exec.js:145:9
    at ChildProcess.exithandler (node:child_process:410:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

### System version

win11

### Node.js version

v16.19.1

### Minimal reproduce step

pake https://weekly.tw93.fun --name Weekly --transparent

### What did you expect to see?

1

### What did you see instead?

1

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
有按照这个配置吗？https://github.com/tw93/Pake/blob/master/bin/README_CN.md#windowslinux-%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by tw93** [comment]
一周没有回复，先关闭，假如问题还没有解决，辛苦直接打开这个issue就好
