### ISSUE TITLE
这个项目和直接在浏览器里面打开有什么区别

### ISSUE THREAD

**Issue by liudonghua123** [tw93/pake#5]
你好，这个项目没有打包静态文件，好像相当于调用API打开网址浏览网页，这个和直接在浏览器里面打开有什么区别

**Comment by tw93** [comment]
没啥区别，相当于快速做了一个网页mac app，不适合所有场景，更适合那种本来应该是一个mac app 但是没有做的那种 如 微信读书 京东阅读 类似的
