### ISSUE TITLE
卡在Compiling app

### ISSUE THREAD

**Issue by for-the-zero** [tw93/Pake#502]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

newest

### System version

win10 1909

### Node.js version

16.15.0

### Minimal reproduce step

pake ... --icon ...

### What did you expect to see?

正常编译

### What did you see instead?

卡住不动

### Anything else?

`Compiling app v0.1.0 (C:\Users\ftz\AppData\Roaming\npm\node_modules\pake-cli\src-tauri)`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
第一次应该比较慢，后面就快了，后面好了吗

**Comment by for-the-zero** [comment]
好了
