### ISSUE TITLE
[Bug] 其中压缩包下载失败

### ISSUE THREAD

**Issue by WindSing-zhang** [tw93/Pake#505]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

master 
 Downloading https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
       Error failed to bundle project: `https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip: Network Error: Network Error: Error encountered in the status line: 由于连接方在一段时间后没有正确答复或连接的主机 没有反应，连接尝试失败。 (os error 10060)`

### System version

win10

### Node.js version

16.9.0

### Minimal reproduce step

1

### What did you expect to see?

能否解决

### What did you see instead?

阿斯顿

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by WindSing-zhang** [comment]
Downloading https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
       Error failed to bundle project: `https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip: Network Error: Network Error: Error encountered in the status line: 由于连接方在一段时间后没有正确答复或连接的主机 没有反应，连接尝试失败。 (os error 10060)`

**Comment by tw93** [comment]
全局科学上网试试，看起来是被拦了

**Comment by WindSing-zhang** [comment]
已解决
