### ISSUE TITLE
[Bug] 套了cloudflare的网站打包后被拦截了，无法正常进入页面

### ISSUE THREAD

**Issue by GotoFox** [tw93/Pake#511]
### Search before asking

- [x] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.0.6

### System version

win11

### Node.js version

16

### Minimal reproduce step

套cloudflare后再打包成功，安装好后正常打开被拦截，无限拦截

### What did you expect to see?

正常进入页面

### What did you see instead?

被cloudflare拦截

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
方便给一个页面吗？我这边测试一下

**Comment by GotoFox** [comment]
> 方便给一个页面吗？我这边测试一下

好的，大佬可以测试一下：chat.ifasto.eu.org
