### ISSUE TITLE
[Bug] 为啥内存都这么高？

### ISSUE THREAD

**Issue by DreamsCat** [tw93/Pake#513]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

最新版本

### System version

macos 13.4.1

### Node.js version

不知道

### Minimal reproduce step

。

### What did you expect to see?

内存占用不用太高

### What did you see instead?

。

### Anything else?

![image](https://github.com/tw93/Pake/assets/52805134/1e391d79-dca6-4e42-81b1-c2673fa17f79)
会存在一个 300MB 左右的，我看用这个打包的软件，都会有，请问这个是啥？浏览器内核吗？占用的内存确实比较大

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
正常，因为最终还是一个网页包裹，不过很多时候也很取决于原有页面的内容管理，不过这个还是比electron好不少，参考这个https://tauri.app/zh-cn/v1/references/benchmarks/#%E5%86%85%E5%AD%98%E7%94%A8%E9%87%8F
