### ISSUE TITLE
希望在mac下添加一个设置，能关闭窗口时隐藏窗口而不是最小化窗口

### ISSUE THREAD

**Issue by veryqun** [tw93/Pake#516]
### Search before asking

- [x] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

在mac中点击左上关闭按钮会最小化，但是最小化不一定适合所有网页，能否添加选择为隐藏窗口（但不完全退出）,这样可能会赏心悦目很多

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
有道理，这个我加一个稀有参数试试，我下一个版本加上，你说的这个是命令行打包的情况吧

**Comment by veryqun** [comment]
是的，我是用命令行打包的。

**Comment by tw93** [comment]
我想了想，请问现在Mac软件上有类似的软件吗？我试了试突然感觉有些奇怪，或许你可以试试 command +h 是不是可以满足使用

**Comment by veryqun** [comment]
比如spotify，网易云音乐，微信，chrome，这些应用的最后一个窗口关闭后，应用不会终止，会在dock图标中下标黑点存在。但是也不会最小化占用dock栏的空间。

**Comment by veryqun** [comment]
这是我找到的一点参考，不知道有没有帮助作用 ^.^

> 在 macOS 中，常见的应用行为是，当用户点击应用窗口的关闭按钮时，应用并不真正退出，而只是将窗口关闭并在后台运行。这样可以使应用在下次打开时响应更快。要在你的 macOS 应用中实现这种行为，你可以使用 Swift 和 Cocoa 框架。
> 
> 以下是一个简单的方法来实现这一功能：
> 
> 1. 打开你的项目并选择你的应用的 `AppDelegate.swift` 文件。
> 
> 2. 为 `NSApplicationDelegate` 添加以下方法：
> 
> ```swift
> func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
>     return false
> }
> ```
> 
> 返回 `false` 表示当应用的最后一个窗口关闭后，应用不应该终止。
> 
> 3. 如果你希望应用的图标在 Dock 栏上仍然可见，并让应用在点击 Dock 图标时重新打开主窗口，你需要在 `AppDelegate.swift` 中添加额外的逻辑。
> 
> 例如，如果你有一个名为 `mainWindow` 的 `NSWindow` 属性，你可以使用以下代码：
> 
> ```swift
> @IBOutlet weak var mainWindow: NSWindow!
> 
> func applicationDidFinishLaunching(_ aNotification: Notification) {
>     // 初始化代码...
> }
> 
> func applicationShouldHandleReopen(_ sender: NSApplication, hasVisibleWindows flag: Bool) -> Bool {
>     if !flag {
>         mainWindow.makeKeyAndOrderFront(nil)
>     }
>     return true
> }
> ```
> 
> 在这个例子中，`applicationShouldHandleReopen` 是当应用重新激活时调用的。如果没有可见的窗口 (`flag` 为 `false`)，我们手动将 `mainWindow` 重新置于前端并激活。
> 
> 确保你的 `mainWindow` 已经与 Interface Builder 中的窗口连接，或者你需要其他方法来获取到主窗口的引用。
> 
> 这就是基本的设置，你可能需要根据你的具体需求进行调整。

**Comment by JadeVane** [comment]
Linux下应该也可以实现这个功能，能否也做适配
