### ISSUE TITLE
[Feature Request]: 关于视频全屏

### ISSUE THREAD

**Issue by Becods** [tw93/Pake#525]
### Search before asking

- [ ] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

近日在打包jellyfin客户端，发现视频无法全屏

并且找到了这两个相同问题的issue https://github.com/tw93/Pake/issues/402#issuecomment-1521039765 https://github.com/tauri-apps/tauri/issues/1139#issuecomment-757535710

### Solution

深入研究过程中，我发现了这个issue https://github.com/tauri-apps/tauri/issues/4748#issuecomment-1472034745

```
import { appWindow } from "@tauri-apps/api/window";

document.addEventListener("fullscreenchange", () => {
  if (document.fullscreenElement) {
    appWindow.setFullscreen(true);
  } else {
    appWindow.setFullscreen(false);
  }
});
```

以及同样是使用tauri作为框架的[prayag17/JellyPlayer](https://github.com/prayag17/JellyPlayer/blob/main/src/routes/player/videoPlayer.jsx#L522-L529)中发现了这段代码的使用，并且经过测试是可以完美全屏的

```
onClick={async () => {
	let fstate =
		await appWindow.isFullscreen();
	setAppFullScreen(!fstate);
	await appWindow.setFullscreen(
		!fstate,
	);
}}
```

那么理论上是可以通过注入这段代码，来实现全屏支持的

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
太感谢了，我去试试看

**Comment by Becods** [comment]
发现在 https://github.com/tw93/Pake/commit/822c12fa19e557500640e1bd89df1e180ff47348 已加入双击全屏的功能

关闭此issue
