### ISSUE TITLE
[Bug] 打开链接竟然跳到外部默认浏览器，不可思议

### ISSUE THREAD

**Issue by jkwroi24io9342fsdjklAdf** [tw93/Pake#527]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.2.1

### System version

macos 13.4

### Node.js version

16

### Minimal reproduce step

封装知乎，登录，然后打开里面的问题，会跳到外部浏览器

### What did you expect to see?

希望在当前APP中打开

### What did you see instead?

在默认浏览器中打开问题的回答，并需要登录

### Anything else?

如果在应用里面登录了，比如知乎，但是点击问题的回答时打开新页面的时候，竟然要跳到默认浏览器去打开(默认浏览器没登录)，这实在是太尴尬了..., 这种场景压根没法用

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
其实这种场景就不是Pake的打包场景，为啥需要打包知乎，其实更适合单页面工具的场景

**Comment by jkwroi24io9342fsdjklAdf** [comment]
看场景确实是只适合单页面打包，但是很多场景都是多页面的，作为工具，能够适应多场景是更好的吧，一点儿个人的想法

**Comment by tw93** [comment]
谢谢提醒，已经修复你说的这个问题，的确可以适应多场景的，辛苦直接使用  Pake-cli 2.3.1 版本即可

**Comment by htnanako** [comment]
2.3.1版本 打包了一个私有部署的软件 多页面还是会跳外部浏览器。只有首页能留在app里。

**Comment by jkwroi24io9342fsdjklAdf** [comment]
还有比如知乎回答页面，点击标题链接的时候并不会在本页面打开问题主题

**Comment by kdxq** [comment]
上周还可以在页面里面打开网页，现状直接跳到默认浏览器打开了

**Comment by chenxch** [comment]
> 2.3.1版本 打包了一个私有部署的软件 多页面还是会跳外部浏览器。只有首页能留在app里。

您好，这个问题您那是否已解决
