### ISSUE TITLE
[Bug] 在线编译无法获取安装包，显示异常

### ISSUE THREAD

**Issue by longchent** [tw93/Pake#541]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

使用在线编译异常，以至于不显示附件：
[windows-latest](https://github.com/longchent/Pake/actions/runs/5748325185/job/15580971746#step:11:11)
No files were found with the provided path: node_modules/pake-cli/output/*. No artifacts will be uploaded.

### System version

显示官方教程最新版本

### Node.js version

显示官方教程最新版本

### Minimal reproduce step

显示官方教程最新版本

### What did you expect to see?

麻烦作者大大解决下

### What did you see instead?

麻烦作者大大解决下

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
```javascript
node cli.js https://57cool.cool/ --name 57号同学 --icon icon.ico --height 780 --width 1200 --show-system-tray
```
如果要使用默认图标，在线编译时请不要配置 `icon`，去除 `--icon icon.ico` 重新编译试试
@longchent

**Comment by Tlntin** [comment]
感觉是包名出现中文引起的。

**Comment by tw93** [comment]
不要使用中文，假如有问题，辛苦再打开这个issue就好

**Comment by Desdemo** [comment]
我刚遇到了，我是因为应用名带了空格，去掉就好了

**Comment by xiaosai12** [comment]
为什么我去掉空格也不行，一直报错

**Comment by Tlntin** [comment]
> 为什么我去掉空格也不行，一直报错 windows可以，mac不行

`icon:  /Users/simon/Downloads/f991212246865c89f7087fa543e73517_Google_Docs.icns`你这图标不能用本地路径，得上传到第三方图床，再提供链接。

**Comment by a10086111** [comment]
No files were found with the provided path: node_modules/pake-cli/output/*. No artifacts will be uploaded.
我name没有使用中文也这样报错 无法下载

**Comment by ryannewcomer** [comment]
hi, some problem here

**Comment by wojing** [comment]
> No files were found with the provided path: node_modules/pake-cli/output/*. No artifacts will be uploaded. 我name没有使用中文也这样报错 无法下载

同样， icon用了rawcontent.github 的ico图片

**Comment by zzh4141** [comment]
https://github.com/zzh4141/Pake/actions/runs/15527884436/job/43710781977  有没有大佬帮我看看我这个？图标使用的是我自己公开的s3
