### ISSUE TITLE
Windows平台窗口置顶功能

### ISSUE THREAD

**Issue by when-hao** [tw93/Pake#544]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

我在issue、discussions、code都找不到相关内容，希望能够添加这个功能:

使用pake打包windows平台的程序能够支持窗口置顶功能（也叫做  始终在最前面、keep on top 或者 always on top），即让程序覆盖在其他窗口的上层

### Solution

我不会rust，但在百度上搜索到的可能的解决方法
https://www.5axxw.com/questions/simple/dusdne
https://www.5axxw.com/questions/simple/2sjrvp

### Anything else?

nothing

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
的确有这个方法，下一个版本我加一下，请问你的使用场景是什么？
