### ISSUE TITLE
feat:  请支持下语雀，mac版的体验可太烂了

### ISSUE THREAD

**Issue by xckevin** [tw93/Pake#55]
很好的项目，请支持下语雀吧

**Comment by tw93** [comment]
安排
内网还是外网🤣

**Comment by xckevin** [comment]
hhh 明白人，外网的吧

> 安排 内网还是外网🤣

**Comment by tw93** [comment]
[YuQue.dmg.zip](https://github.com/tw93/Pake/files/9938567/YuQue.dmg.zip)
[AliYueQue.dmg.zip](https://github.com/tw93/Pake/files/9938566/AliYueQue.dmg.zip)
试试，希望你喜欢，哈哈哈

**Comment by tw93** [comment]
语雀自己页面有更新，pake适配更新了下，可以用release里面的最新版本，https://github.com/tw93/Pake/releases/latest/download/YuQue.dmg

**Comment by alswl** [comment]
@tw93 Yuque 打包需要特别的参数么？我打包出来总是会侧边栏 Panic。

**Comment by alswl** [comment]
遇到的错误是：
```
IPC custom protocol failed, Tauri will now use the postMessage interface instead
```
