### ISSUE TITLE
Mac端左上角三个按钮，能不能做成实际功能？而不是一个摆设，点击任何按钮都是最小化

### ISSUE THREAD

**Issue by 0liragunse** [tw93/Pake#550]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

据我所知，Chrome是支持后台运行的，就是关掉了所有窗口之后，程序并没有退出，还在后台运行。

那么打包之后的程序能不能把三个按钮做成真实的功能呢？

如图：
<img width="149" alt="image" src="https://github.com/tw93/Pake/assets/136149960/2eb45ffb-4598-4887-b788-7db247df6e61">

点击x就是关闭窗口，但是保持后台运行
点击-就是最小化
点击第三个点就是全屏

就是跟Mac上的程序的操作逻辑是一样的。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
抱歉 这个其实之前是有讨论过，Pake 更多是工具参加，比如说你见到的很多常驻工具，其实点击x以后，是最小化，比如你可以看看常见的 音乐、im类的应用，这里其实有纠结过的，不过当前还是保持了这个做法
假如退出，建议就用 command+q
还有一种办法，可以给我来提pr，一起看看效果
