### ISSUE TITLE
[Bug] 单页面程序，跳转到默认浏览器打开（升级2.3.1后发生）

### ISSUE THREAD

**Issue by kdxq** [tw93/Pake#553]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.3.1

### System version

windows

### Node.js version

14

### Minimal reproduce step

正常打包就这样了

### What did you expect to see?

![image](https://github.com/tw93/Pake/assets/43022212/c1380785-db99-4393-b2a4-af2ae4a84088)

### What did you see instead?

点击标签就弹出新的网页了

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by kdxq** [comment]
之前装的2.3.0，是正常的，运行后，打开新的标签也在程序界面内打开。今天升级到了2.3.1，打包运行后，新的标签页就开始弹出到默认浏览器中打开了。尝试将2.3.1降级到2.3.0，但依然无效，还是在浏览器中打开新的标签页

**Comment by abcmiao** [comment]
> 之前装的2.3.0，是正常的，运行后，打开新的标签也在程序界面内打开。今天升级到了2.3.1，打包运行后，新的标签页就开始弹出到默认浏览器中打开了。尝试将2.3.1降级到2.3.0，但依然无效，还是在浏览器中打开新的标签页

我也遇到同样的问题

**Comment by tw93** [comment]
谢谢反馈，方便给一下对应的页面地址吗？我看看，同时帮忙看看对应的跳转逻辑是什么样子的

**Comment by kdxq** [comment]
@tw93 我的系统是基于ruoyi 框架开发的，我刚刚测试了  https://vue.ruoyi.vip/  这个网站，也存在同样的问题。您可以用这个网站测试一下。

**Comment by tw93** [comment]
感谢反馈 晚上我去试试

**Comment by kdxq** [comment]
您太快了，感谢

**Comment by kdxq** [comment]
![image](https://github.com/tw93/Pake/assets/43022212/4a0e53c3-75c6-418a-8e70-75307a5c18b5)
上面这个条的颜色可以改吗？不然有点丑；
另外，可以打包为直接运行的exe吗，不需要安装的那种？

**Comment by kdxq** [comment]
@tw93 
能回复一下上面的两个问题吗？感谢

**Comment by kdxq** [comment]
@tw93 我测试了，2.3.2版本是正常的，感谢您的付出

**Comment by tw93** [comment]
@kdxq windows的标题栏不好改，也不好隐藏，不过 mac 的可以隐藏掉，做成沉浸式的效果，你可以看看官方 Pake 打包的应用
> 可以打包为直接运行的exe吗，不需要安装的那种？ 抱歉，我手上没有 windows 电脑，exe单文件看起来底层是支持的，不过 Pake 本身没有支持，不过这里 tauri 说是不保证 exe 的稳定性
