### ISSUE TITLE
支持一个主窗口内创建多个子窗口吗？

### ISSUE THREAD

**Issue by moom-en** [tw93/Pake#554]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

支持一个主窗口内创建多个子窗口吗？就跟浏览器一样，多个子窗口通过页签来管理，而并非N个独立的窗口，很不好管理

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Tlntin** [comment]
你说的这个应该不支持

**Comment by tw93** [comment]
不支持，后面应该也不会支持，因为 Pake 最终还是想着简单一点儿，和浏览器有很大区别
