### ISSUE TITLE
[Bug] 部分页面跳转白屏

### ISSUE THREAD

**Issue by abcmiao** [tw93/Pake#555]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.3.2

### System version

macos 13.5

### Node.js version

18

### Minimal reproduce step

<img width="1202" alt="image" src="https://github.com/tw93/Pake/assets/13944985/7615755f-ad5c-425f-8ae1-2469278e67c2">

这个网址：https://imagestool.com/zh_CN/

打包后，双击抬头的图标，跳转一次，再双击，跳转就白屏

### What did you expect to see?

这是个点击跳转首页，应该可以无限点击

### What did you see instead?

现在点两次就白屏了

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by abcmiao** [comment]
<img width="1202" alt="image" src="https://github.com/tw93/Pake/assets/13944985/2455258e-197b-4c18-8394-2acc5076dd4e">
很容易复现

**Comment by abcmiao** [comment]
频繁点击，也会出现。刚在操作压缩图，在切换抬头菜单的其他功能时，又出现白屏，只能关掉再打开

**Comment by abcmiao** [comment]
<img width="1192" alt="image" src="https://github.com/tw93/Pake/assets/13944985/9746b815-d938-4d12-8474-df10762bd393">
在打包好的客户端出现处理失败的情况，但是在网页端没事，有点难搞奥。操作：压缩图片到指定大小    -  一个3M大小的截图压缩到200KB以下

**Comment by tw93** [comment]
这两个问题看起来是这个网站和 wkwebview 容器的兼容问题，你可以试试用Safari去调试，应该会是一样的效果，等到Safari使用ok了，Pake 这边应该默认就好了
