### ISSUE TITLE
[Bug] windows 的 qwerty 安装包并不能最小化视窗, 一直处于全屏状态

### ISSUE THREAD

**Issue by zhuoqinyue** [tw93/Pake#563]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.3.2

### System version

win10

### Node.js version

14.18

### Minimal reproduce step

![image](https://github.com/tw93/Pake/assets/64182179/11b122c4-c6cf-4e98-b7fd-2d543f24b9b2)
如图所示, 一直处于全屏状态, 按照浏览器的热键不能退出全屏, 只有Alt + F4退出程序是有效的

### What did you expect to see?

能否出一个最小化最大化的热键

### What did you see instead?

![image](https://github.com/tw93/Pake/assets/64182179/11b122c4-c6cf-4e98-b7fd-2d543f24b9b2)
如图所示, 一直处于全屏状态, 按照浏览器的热键不能退出全屏, 只有Alt + F4退出程序是有效的

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by iFTY-R** [comment]
我有遇到过这种情况，cli打包跟pake都配置了 fullscreen为false，但是安装之后全屏

感觉像是 tauri 的 bug

**Comment by Tlntin** [comment]
我周末试试

**Comment by Yakima-Teng** [comment]
我这可以重现这个bug，执行的命令是pake https://www.example.com --name example-v1 --icon build/icon.ico --user-agent browser-example，不过在执行这个命令之前我是先执行了类似的但是增加了 --hide-title-bar --fullscreen这两个参数的，是不是本地缓存的数据导致新的配置项没有生效。

**Comment by Yakima-Teng** [comment]
> 我周末试试，测试完成，没遇到。可能是你的nodejs版本太低了。

我的node版本是v20.12.0，不低。
