### ISSUE TITLE
[Bug] Mac 不能拖动窗口

### ISSUE THREAD

**Issue by FocusCare** [tw93/Pake#568]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.3.2

### System version

<img width="392" alt="image" src="https://github.com/tw93/Pake/assets/3634726/2dca9fd9-4abe-416f-9cd4-ccda42f07610">

### Node.js version

18.17.1

### Minimal reproduce step

无法拖动窗口
<img width="644" alt="image" src="https://github.com/tw93/Pake/assets/3634726/c81bb747-b007-4b00-8494-0e35174b63b9">

### What did you expect to see?

可正常拖动窗口

### What did you see instead?

N/A

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
这种情况一般是 dangerousRemoteDomainIpcAccess 配置不对，你打包的网页地址是什么，需要检查一下，然后看看是不是页面本身有重定向，去了其他的地方
查看这个 https://github.com/tw93/Pake/blob/master/src-tauri/tauri.conf.json#L11
此外Pake cli 里面放出了配置
https://github.com/tw93/Pake/blob/master/bin/README_CN.md#safe-domain

假如还有问题，辛苦直接打开这个issue

**Comment by xiaoshengwpp** [comment]
如果 多个 域名 domain 怎么配置 domain：‘sad,asd2’貌似不生效
