### ISSUE TITLE
🔴 发现「okso」在线白板比「Witeboard」要好用

### ISSUE THREAD

**Issue by Thomas-Harrell** [tw93/Pake#57]
### [okso：https://okso.app/](https://okso.app/)

发现「okso」比「Witeboard」好用很多

「Witeboard」用快捷键才能画「矩形」、「圆」

「Witeboard」需要重新开启应用才能刷新白板

使用快捷键的话会弹出系统的「提示音效」，这点挺烦的

**Comment by tw93** [comment]
谢谢推荐 我去试试 如果更好就替换哦
