### ISSUE TITLE
[Bug] i get a error when type command pake

### ISSUE THREAD

**Issue by LanHuangJG** [tw93/Pake#572]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

![image](https://github.com/tw93/Pake/assets/125177842/e407731c-dece-42dc-ac02-755a2922bee4)

### System version

![image](https://github.com/tw93/Pake/assets/125177842/c55be92f-0d92-4cfb-8f99-0c61cb41ef2e)

### Node.js version

![image](https://github.com/tw93/Pake/assets/125177842/6130ced8-f0e6-4c06-802f-dfb4e7b15521)

### Minimal reproduce step

1.start powershell
2.type pake then enter

### What did you expect to see?

run normally

### What did you see instead?

run error

### Anything else?

no

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tw93** [comment]
Try node version 18.17.0, uninstall it and reinstall Pake-cli
