### ISSUE TITLE
可以打包本地的html/css/js

### ISSUE THREAD

**Issue by liudonghua123** [tw93/Pake#575]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

如果本地开发了一些使用html/css/js的小工具,小应用,并没有部署在网络上,如果这个工具支持,那就可以替换 https://github.com/tauri-apps/tauri-action

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Tlntin** [comment]
不是已经支持了吗？

**Comment by Tlntin** [comment]
https://github.com/tw93/Pake/blob/master/bin/README_CN.md#url

![image](https://github.com/tw93/Pake/assets/28218658/6e894791-2af7-4073-ae1e-172cf5e740f8)

![image](https://github.com/tw93/Pake/assets/28218658/dbc69ba0-c593-4330-95ca-d7ffd5bf6e38)

**Comment by liudonghua123** [comment]
> https://github.com/tw93/Pake/blob/master/bin/README_CN.md#url
> 
> ![image](https://github.com/tw93/Pake/assets/28218658/6e894791-2af7-4073-ae1e-172cf5e740f8)
> 
> ![image](https://github.com/tw93/Pake/assets/28218658/dbc69ba0-c593-4330-95ca-d7ffd5bf6e38)
> 

不好意思，当时没仔细看

如果是本地路径是目录 还是 index.html 的文件完整相对/绝对路径？

建议文档中可以可以详细说明以下

**Comment by Tlntin** [comment]
我忘记了，你可以试试，应该是目录吧。

**Comment by Tlntin** [comment]
已补充，可以参考该[wiki: Pake打包静态文件示例](https://github.com/tw93/Pake/wiki/Pake%E6%89%93%E5%8C%85%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6%E7%A4%BA%E4%BE%8B)进行打包。
