### ISSUE TITLE
feat: 可以搞个CyberChef吗？另外可以支持本地静态html吗

### ISSUE THREAD

**Issue by yaoxinghuo** [tw93/Pake#58]
[CyberChef](https://github.com/gchq/CyberChef)
有两个版本，可以是在线版，最好是下载了release用离线本地版。
谢谢！

**Comment by tw93** [comment]
这个很简单，建议你直接fork后，直接自己按照文档配置几行代码就ok啦
你说的这个工具，我之前打包过一个类似的，你可以试试，更好看一些
https://github.com/tw93/Pake/releases/download/V0.6.0/Tools.dmg
