### ISSUE TITLE
mac没问题  win好像有个路径报错。[Bug] 

### ISSUE THREAD

**Issue by onlinedear** [tw93/Pake#580]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

最新的版本[version  2.3.3]

### System version

macOS Sonoma 版本14.0 Beta版(23A5301h)

### Node.js version

我用的Github在线生成

### Minimal reproduce step

![image](https://github.com/tw93/Pake/assets/10751712/775a4085-64d9-4b5a-9891-1cb2f00b9ab5)

### What did you expect to see?

![image](https://github.com/tw93/Pake/assets/10751712/94dbd604-104d-404a-ac24-700f3f24d14c)

### What did you see instead?

![image](https://github.com/tw93/Pake/assets/10751712/a5d30094-0043-4898-b536-dd7e71c20d73)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Mekako** [comment]
![image](https://github.com/tw93/Pake/assets/113497377/c4d0347e-a892-46c9-91d6-3cf6e912378f)
同样的问题，蹲一下

**Comment by Mekako** [comment]
这个issuehttps://github.com/tw93/Pake/issues/541是同样的问题，我把中文文件名改了就好了，希望对你有帮助

**Comment by IonTeLOS** [comment]
while building Linux artifacts and having similar issue, I found out that the build is silently failing, thus not producing any artifacts. Looking through the logs I discovered that the --resize argument is irrelevant and causing the error. I removed the relevant block from the workflow script and it is working now

**Comment by onlinedear** [comment]
> 这个issue #541 是同样的问题，我把中文文件名改了就好了，希望对你有帮助

我用的是英文的包名。

**Comment by kiterza** [comment]
你应该重新打开这个问题
