### ISSUE TITLE
[Bug] chatgpt客户端进入全屏后无法退出

### ISSUE THREAD

**Issue by qinywolf** [tw93/Pake#582]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

v2.3.2 chatgpt，项目Releases中的chatgpt客户端。
### Anything else?

擦键盘不知道触发了什么按键，导致chatgpt客户端进入全屏后无法退出，使用了浏览器F11无法退出全屏。

**Comment by tw93** [comment]
可以点击左上角的按钮试试就好了，有一个放大缩小的按钮，假如还是有问题，可以试试command+q退出即可
