### ISSUE TITLE
Open file with packaged app

### ISSUE THREAD

**Issue by alswl** [tw93/Pake#584]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

I want open the file (eg. excalidraw file)  in the packaged app.

Currently, the official website( https://excalidraw.com/ ) provide an Chrome Web App, it can open local file in the macOS.

But if I packaging with pake, I cannot open the file by packaged app.

The error message is:

> The document “ceresdb-on-cloud-2023-05-16-1926.excalidraw” could not be opened. Excalidraw cannot open files of this type.

This is my packaging command:

```sh
pake https://excalidraw.com/ --name Excalidraw --icon ~/Downloads/logo256.icns --transparent
```

### Solution

I want open the `.excalidraw` file by right click (Open With) Excalidraw (the packaged app).

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by alswl** [comment]
Related issues:

- https://github.com/tauri-apps/tauri/issues/3736
- https://github.com/tauri-apps/tauri/issues/918
- https://github.com/tauri-apps/tauri-docs/issues/1526

**Comment by tw93** [comment]
Thanks for the feedback, I'll take a look at this when I have time
