### ISSUE TITLE
ChatGPT new UI unsupport [Bug] 

### ISSUE THREAD

**Issue by Maxx-Yang** [tw93/Pake#595]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

1.0.0

### System version

MacOS 14

### Node.js version

The lastest version

### Minimal reproduce step

When I click the 'New Chat' or the history chat list, it will not open in the Pake, it will open in my default broswer.

### What did you expect to see?

All behavior should be in the Pake but on my default browser.

### What did you see instead?

Some behavior happens on my default browser.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
适配ChatGPT最新版本的Pake打包mac安装包，使用的小伙伴可以替换试试，Pake官方全局版本等都优化好了来更新
[ChatGPT_2.dmg.zip](https://github.com/tw93/Pake/files/13334887/ChatGPT_2.dmg.zip)

**Comment by Maxx-Yang** [comment]
好的，先试试
