### ISSUE TITLE
通过标题栏拖动窗口存在一些问题

### ISSUE THREAD

**Issue by liby** [tw93/Pake#6]
## 问题描述
我发现代码中设置了 `with_titlebar_transparent`，同时也发现代码中有做 `drag_window` 的监听事件，但使用下来，发现窗口依旧很难通过标题栏拖动，只有在左上角的特定位置可以进行拖动，很难找到这个点

https://user-images.githubusercontent.com/38807139/195969685-aed017f9-c21f-44cf-8ebd-630bf9956788.mp4

**Comment by tw93** [comment]
打开 with_devtools 111 和116行这边可以打log调试，你试试看

**Comment by liby** [comment]
> 打开 with_devtools 111 和116行这边可以打log调试，你试试看 我当时那个主要是用于兼容 微信和微信读书场景的🐶

额，控制台我打开了，触发不了 `drag_window` 事件。
跟微信和微信读书没啥关系（你可以试试，只有在左上角一个特别的位置可以拖动），`drag_window` 是加在 `topDom` 上的不是，跟里面套的东西没啥关系，就是设置了 `with_titlebar_transparent` 导致选不到标题栏，然后没法拖动窗口了，要自己做拖动的 handler 了

**Comment by tw93** [comment]
https://user-images.githubusercontent.com/8736212/195970304-3c0899f0-8048-4f4f-b137-9a6fe03888bb.mp4

看视频

**Comment by liby** [comment]
> 1212.mp4 
> 看视频

MacBook Pro (16-inch, 2019) 2.3 GHz 8-Core Intel Core i9
https://user-images.githubusercontent.com/38807139/195970505-a61297f8-a275-4e9f-a4fa-c3a8d7f99456.mp4

**Comment by tw93** [comment]
原来如此 我懂了 很感谢反馈，不过我手边没有鼠标，辛苦帮忙调试调试，可以直接pr

**Comment by tw93** [comment]
pull 下最新的代码，再试试～

**Comment by liby** [comment]
> pull 下最新的代码，再试试～

🚀，可以了，怪不得之前控制台能看到 `SyntaxError: Unexpected token '.'` 的报错。
我还以为是 https://github.com/tw93/Pake/blob/4a35b0cd19e5c99d01ef6e43fccb8df06ef24c66/src-tauri/src/main.rs#L68 这一行是多写了，没往它少了对应的起始符号想

**Comment by tw93** [comment]
我的锅
