### ISSUE TITLE
 help: message: icon tldraw.png is not RGBA

### ISSUE THREAD

**Issue by jakbin** [tw93/Pake#600]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.3.5

https://github.com/jakbin/tldraw-desktop/actions/runs/6922338068/job/18828946092

### System version

ubuntu-latest

### Node.js version

18

### Minimal reproduce step

i try to make desktop app of 'https://tldraw.com/' and i download icon for that from 'https://github.com/tldraw' .

you can see full log here :- https://github.com/jakbin/tldraw-desktop/actions/runs/6922338068/job/18828946092

### What did you expect to see?

it should set that icon file 

### What did you see instead?

i got error .

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
@jakbin  Your inquiry seems to be related to the strict constraints of using PNG format icons in Tauri. Perhaps you could attempt to address the issue by manipulating your PNG icons?

Issues and pr: https://github.com/tauri-apps/tauri/pull/6712

Plz see this doc: https://tauri.app/v1/guides/features/icons/
