### ISSUE TITLE
Option to ignore certificate errors (e.g. localhost and self signed certificate causing error "TLS certificate unacceptable")

### ISSUE THREAD

**Issue by AgentSmith0** [tw93/Pake#603]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

When on localhost or using self signed certificates, the error "TLS certificate unacceptable" appears.

### Solution

Nativefier has an option to disable those errors (https://github.com/nativefier/nativefier/blob/master/API.md#ignore-certificate).
Would be nice to also implement such a feature.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
This is an issue with Tauri. Perhaps you can refer to this issue for a solution:
https://github.com/tauri-apps/tauri/issues/4039
