### ISSUE TITLE
建议增加全局热键、Pin、Menubar等提升效率和体验的默认功能

### ISSUE THREAD

**Issue by yinheng-gh** [tw93/Pake#613]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

我的想法初衷是：通常人们如果需要把某个网页打包成本地应用，那么这个应用应该是一个高频应用，所以增加一些通用的，能够提升效率的功能，应该会很不错的。

### Solution

以ChatGPT为例，我们通常会把它当成一个Copilot随时呼出和使用，所以我建议增加如下功能：
1. 全局热键：可以随时呼出和隐藏，这对于一个Copilot应用来说很重要。当然，有很多其它工具可以做这个事，比如我现在用的是Raycast来设置，但Pake直接内置此功能会对普通用户方便很多。
2. Pin to top：这个Issue中有人提过，就是置顶，位于所有窗口之上。用处呢，就是有时候我们在ChatGPT中问出一些问题，然后要边看答案，边去另一个操作窗口中修改什么的，这时候ChatGPT一直在最上，就很重要。当然，Unpin也同样重要，所以最好能设置一个快捷键来做这个事，比如alt+p后，就pin了（这个可以让用户设置）
3. 放置到Menubar中：这个就不多说了，很多高频应用都可以从Menubar中呼出（Mac中，Windows中好像也是吧？），如果能做到这个，还是很不错的。

### Anything else?

其它的应该还有很多，想起来再提。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by hallestar** [comment]
上面提到的**Pin to top**, 如果是windows的话，用`PowerToys`的**始终置顶**, 就能实现了

当然如果Pake原生支持并且跨平台就更棒

**Comment by tw93** [comment]
请升级pake-cli到2.4.0的版本，大部分都支持了
--always-on-top 
--activation-shortcut
----show-system-tray

详细可见文档：https://github.com/tw93/Pake/blob/dev/bin/README.md#activation-shortcut
