### ISSUE TITLE
可以做一个网页，更适合新手用户

### ISSUE THREAD

**Issue by wChenonly** [tw93/Pake#619]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

看到一个这个 https://webdesk.pigjs.com/builder/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Tlntin** [comment]
网站是有想法，但是费钱，后面就无限搁浅了。
试玩了一下你的那个网站，Mac版下载看来要收费呀，估计大部分人会不愿意。
![image](https://github.com/tw93/Pake/assets/28218658/e10129f4-2604-4ea6-b9a8-ace5319e6a4a)

**Comment by wChenonly** [comment]
> 网站是有想法，但是费钱，后面就无限搁浅了。

这个是我看到别人的，好像第一次不需要，我记得我第一次下载不收费

**Comment by guanguan0701** [comment]
我是 webdesk 的作者，使用 https://webdesk.pigjs.com/builder/ 第一次下载不需要 收费的，如果不想付费的话，可以重新打包生成。对 webdesk 有什么建议可以联系我，欢迎给我反馈
![author](https://github.com/tw93/Pake/assets/128672424/ab6e705d-b5fc-499c-96a9-ad401616f973)

**Comment by aiwillcoming** [comment]
可以赞助服务器
