### ISSUE TITLE
Support System Tray

### ISSUE THREAD

**Issue by TinsFox** [tw93/Pake#620]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

When I use apps like YouTube Music, I want to be able to close the window and just keep a system tray

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by abdullah1116** [comment]
yes, please add this when we close the app I will keep running in the background with the system tray to reopen
I will use this on WhatsApp
and also click on the notification to reopen if possible

**Comment by tw93** [comment]
Check out this document
https://github.com/tw93/Pake/blob/master/bin/README.md#show-system-tray

**Comment by wxyttty** [comment]
> 查看此文档 https://github.com/tw93/Pake/blob/master/bin/README.md#show-system-tray

显示也没用，只能和任务栏的同时存在，关闭一个另一个也会关闭，不能关闭后保留托盘

**Comment by artistro08** [comment]
> 显示也没用，只能和任务栏的同时存在，关闭一个另一个也会关闭，不能关闭后保留托盘
> The display is useless. It can only exist at the same time as the taskbar. Closing one will also close the other. You cannot keep the tray after closing.

I gotta agree with the comment above. it works but not in the way it was intended.
