### ISSUE TITLE
有没有可能支持打包安卓app呀?

### ISSUE THREAD

**Issue by libondev** [tw93/Pake#627]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

如题

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
需要等待 tauri 的正式2.0版本发布，就支持了
