### ISSUE TITLE
[Bug] chatgpt can't get through cloudflare. normal browser is fine. Try compile by myself and use exist deb package.

### ISSUE THREAD

**Issue by EveryJin** [tw93/Pake#631]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

lastest

### System version

debian

### Node.js version

-

### Minimal reproduce step

-

### What did you expect to see?

-

### What did you see instead?

-

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gvenusleo** [comment]
I'm having this problem too. I'm using KDE Neon as my operating system. When I use the deb package I compiled, I have specified the value of user-agent.

![Screenshot_20231227_120908](https://github.com/tw93/Pake/assets/79075347/9cd8b246-74a2-403e-b7c3-26abd04e13fe)

**Comment by tw93** [comment]
It seems that this error was intercepted by the chatgpt web page. The only solution here is to change a VPN, including how to determine whether it is a global system proxy.
