### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by binyellow** [tw93/Pake#633]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

latest

### System version

Macos

### Node.js version

latest

### Minimal reproduce step

Wiki中的文档Online-Compilation-(used-by-ordinary-users).md
<img width="989" alt="image" src="https://github.com/tw93/Pake/assets/29519985/42e61af9-3cc4-4f68-975b-c473c1d55d0c">
这里url有错误打开404
_https://github.com/tw93/Pake/blob/master/bin/README_EN.md#usage_
要改成 `https://github.com/tw93/Pake/blob/master/bin/README.md#usage`

### What did you expect to see?

link valid

### What did you see instead?

link invalid

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Tlntin** [comment]
已修复，感谢提醒。
