### ISSUE TITLE
希望添加Chrome浏览器类似的全局文本搜索功能. 或者说能不能Chrome的插件集成进去?

### ISSUE THREAD

**Issue by tanpengsccd** [tw93/Pake#635]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

希望添加搜索功能

### Solution

希望添加搜索功能

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Pake 的底层使用的tauri的能力，我查了查当前还不支持全局搜索，官方有好几个issue了，这一块我会继续关注官方是否支持。
对于使用可以把chrome插件集成进去在这个技术上不太现实，因为本身很轻量，同时内核可以理解是系统的webview，是不支持这一套的。
