### ISSUE TITLE
使用streamlit生成的网页无法使用pake生成应用程序

### ISSUE THREAD

**Issue by hrsxz** [tw93/Pake#636]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

我在我的chatGPT+elevenLabs项目里@https://github.com/hrsxz/chatGPT-elevenLabs@使用了streamlit生成webui，对于这个在本地运行的网页http://localhost:8501/使用pake无法生成对应的windows安装程序。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
试试 https 的地址，或者建议部署到站点上去，访问本地的localhost我没有试过，你可以试试换成你的本机iP看有没有问题
