### ISSUE TITLE
WIKI 请求更新

### ISSUE THREAD

**Issue by aiwillcoming** [tw93/Pake#637]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

wiki中很多内容已经过时，和最新版不符，请求更新

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
谢谢提醒，我过年期间有空就来搞这个事情
