### ISSUE TITLE
gpt用起来好卡啊

### ISSUE THREAD

**Issue by Emyori** [tw93/Pake#638]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

打完字发送后就特别卡，得过一会往上滑一下才能看到回复的内容

### System version

M1，macOS13.2.1

### Node.js version

无

### Minimal reproduce step

每次都这样

### What did you expect to see?

像iOS版顺滑

### What did you see instead?

目前特别卡

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tw93** [comment]
M1电脑不至于太卡，有两个原因，一个是由于当前访问gpt的网络卡了，还有一个是由于你的当前内容实在太多了，chatgpt对于Safari系统的支持没有优化导致，可是事实新开一个聊天看看是否继续卡，不过我使用很多，没有太碰到。
