### ISSUE TITLE
希望在 Linux 上增加 --transparent 支持

### ISSUE THREAD

**Issue by JadeVane** [tw93/Pake#652]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

感谢作者开发 Pake，能摆脱 chrome、还有 firefox 上半残的 PWA 感觉很开心，但上面那个大大的标题栏还是觉得碍眼，很馋 MacOS 上的 --transparent 选项，请问是否有计划支持 Linux？就算只是提供一个选项可以简单地去掉标题栏，然后由前端自行实现相关事件也可以

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
方便截图看看效果吗？我手上没有linux的机器

**Comment by Tlntin** [comment]
linux可能不太行，底层框架(tauri)目前还不支持。

**Comment by tw93** [comment]
参考 @Tlntin 所说，@JadeVane 有兴趣参加Pake的开源不，可以一起看解决问题

**Comment by JadeVane** [comment]
感谢厚爱，不过我就是有空时玩玩，也没经过系统学习，技艺不精，恐难胜任...
