### ISSUE TITLE
希望在打包的时候加入一些js脚本,如油猴脚本

### ISSUE THREAD

**Issue by ChasLui** [tw93/Pake#653]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

比如打包Twitter的同时打包进入沉浸式翻译

### Solution

通过注入现有的油猴js脚本

### Alternatives

现在是采用代理劫持修改html入口文件注入

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
请关注文档提供的 --inject 配置，可以通过该配置项注入本地的一些 js / css 文件到页面中执行。

https://github.com/tw93/Pake/blob/main/docs/cli-usage.md#inject

**Comment by tw93** [comment]
由于Pake是一个通用打包工具，这里很建议用户自己注入js，参考jeasonnow这个
