### ISSUE TITLE
[Bug] Build App With Pake CLI complains "Node.js 16 actions are deprecated."

### ISSUE THREAD

**Issue by RecedingHare** [tw93/Pake#659]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

0e0bbc7

### System version

GitHub Action/Build App With Pake CLI 

### Node.js version

Node.js 16

### Minimal reproduce step

* Followed https://github.com/tw93/Pake/wiki/Online-Compilation-(used-by-ordinary-users)
* Created GitHub Action
* Ran "Build App With Pake CLI" for Windows, Mac and Ubuntu.

### What did you expect to see?

Build file.

### What did you see instead?

Build file (good!) plus warning:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20...

### Anything else?

I don't know if this is a big problem.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
建议使用Node18版本

**Comment by RecedingHare** [comment]
Thank you for the suggestion.
感谢您的建议

I am following [these instructions](https://github.com/tw93/Pake/wiki/Online-Compilation-(used-by-ordinary-users)). [中文版](https://github.com/tw93/Pake/wiki/%E5%9C%A8%E7%BA%BF%E7%BC%96%E8%AF%91%EF%BC%88%E6%99%AE%E9%80%9A%E7%94%A8%E6%88%B7%E4%BD%BF%E7%94%A8%EF%BC%89)

Is it still possible to change the version of Node.js?
是否还可以更改 Node.js 的版本?

Perhaps I shouldn't worry about it.
也许我不应该担心

**Comment by Ricco-L** [comment]
改了node18和node20都会报这个错误

**Comment by aimu2000** [comment]
Indeed it is

**Comment by tw93** [comment]
I know, this includes something you can ignore, it won't affect actual usage, should be some dependencies of GitHub Action itself.

**Comment by ryannewcomer** [comment]
![image](https://github.com/tw93/Pake/assets/88273136/3817727d-a8bc-4f22-89cb-0bd416a07db3)

this does not work anymore. i need to use the cli way
