### ISSUE TITLE
自行编译生成飞书文档无法使用

### ISSUE THREAD

**Issue by CherryLover** [tw93/Pake#66]
我 clone 下来之后，改了 README 里提示的字段，运行起来后，提示浏览器版本过低且无法正常使用飞书文档。

**Comment by tw93** [comment]
需要等底层依赖 tauri 1.2的版本，现在不能修改ua，飞书自己拦截了，等好了，可以关注pake更新

**Comment by RekiDunois** [comment]
更新过后不会提示版本过低了，但是飞书云文档还是无法打开，可以进入列表，但是点击文档没反应。

```
$ pake -V 
1.0.1
```
