### ISSUE TITLE
[Bug] Actions环境编译完，Artfacts没有生成任何可以下载的文件

### ISSUE THREAD

**Issue by liaoxuewei** [tw93/Pake#661]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

n/a

### System version

n/a

### Node.js version

n/a

### Minimal reproduce step

n/a

### What did you expect to see?

按Actions方式打包的文档说明，今天fork了一个最新的代码，用Build App With Pake CLI来打包，成功，但是Artfacts下没有生成任何可以下载的文件。

### What did you see instead?

n/a

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by liaoxuewei** [comment]
![image](https://github.com/tw93/Pake/assets/970765/049c0493-c613-4b66-817c-35d95fd9729f)

**Comment by tw93** [comment]
<img width="1275" alt="image" src="https://github.com/tw93/Pake/assets/8736212/6e20dae5-d58b-4bf3-87f3-f2db16ba4fa9">
错误在这里
