### ISSUE TITLE
App Notifications do not open the app on Windows 11

### ISSUE THREAD

**Issue by artistro08** [tw93/Pake#665]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

v2.3.5

### System version

Windows 11 Build 22631.3155

### Node.js version

v20.11.1

### Minimal reproduce step

Create app with notifications and flags, Get a notification from the app, doesn't open the app.

Command for reference: 
```bash
pake https://messages.google.com/web --name Messages --icon messages.ico --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.2277.112'
```

### What did you expect to see?

I expected the notifications to open in the app

### What did you see instead?

The notifications don't open the app AND they stay persistent in the Notification center unless I explicitly clear them.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Thank you for your feedback. This problem does exist. I looked for tauri itself, https://github.com/tauri-apps/tauri/issues/3698. It seems that it is not supported yet. I recently upgraded Pake to version 2.0. It should be supported after tauri 2.0 is officially released.
