### ISSUE TITLE
tauri也许将增加android/ios支持，有没有可能pake未来也支持移动端app呢？

### ISSUE THREAD

**Issue by heygsc** [tw93/Pake#666]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

本项目是基于tauri打包，根据近期消息，android/ios支持已经提上日程，未来pake会不会有手机端app的支持呢？
https://beta.tauri.app/blog/tauri-2-0-0-beta/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by 1-bytes** [comment]
> 会有计划，等到tauri2.0发布以后会着手，我最近有空周末也会看看

期待大佬支持 IOS和Android！！因为有一些网站除了在电脑上用，在手机上使用频率也挺高的

**Comment by hustcer** [comment]
Any update on this? Thanks

**Comment by qingchunyy** [comment]
有什么进展嘛，非常需要安卓版本

**Comment by assassinliujie** [comment]
同问进展，非常需要这个功能

**Comment by Hello-job** [comment]
进展如何了呢，非常期待

**Comment by Sjj1024** [comment]
> 进展如何了呢，非常期待

可以试试我的PakePlus，已经支持安卓和ios了哦
开源地址：https://github.com/Sjj1024/PakePlus
