### ISSUE TITLE
Support Widevine

### ISSUE THREAD

**Issue by ZorinFoss** [tw93/Pake#671]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

Hi,

Please add support to use Widevine digital rights management (DRM) component to view protected streaming video and other content in the browser.

Thanks,

### Solution

Support Widevine

### Alternatives

Support Widevine

### Anything else?

[Emty File.md](https://github.com/tw93/Pake/files/14381621/Emty.File.md)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Sorry, currently you can test it through Safari because they are using a container. At the same time, I found this post that indicates the underlying dependency Tauri is not supported yet.
