### ISSUE TITLE
对于网页内部下载文件不是太好

### ISSUE THREAD

**Issue by xiaohuwei** [tw93/Pake#673]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

 会直接乱码 建议可以跳到外部浏览器

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
麻烦提供一下复现路径，我这边排查一下。

**Comment by tw93** [comment]
1个多月暂时没有反馈，先关闭，后续有复现可以打开
