### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Mrkk1** [tw93/Pake#674]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

不存在npm run build命令 与md文档内部说明不符

### System version

macos m1

### Node.js version

"node": ">=6.9.0"

### Minimal reproduce step

不存在npm run build命令 与md文档内部说明不符

### What did you expect to see?

不存在npm run build命令 与md文档内部说明不符

### What did you see instead?

不存在npm run build命令 与md文档内部说明不符

### Anything else?

不存在npm run build命令 与md文档内部说明不符

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
https://github.com/tw93/Pake/blob/master/package.json 在源文件中是有 build script 的，请仔细排查一下是不是使用方式有问题。
