### ISSUE TITLE
[Bug] release包里小红书应用的标题栏无法拖动

### ISSUE THREAD

**Issue by zty5678** [tw93/Pake#693]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

[V2.3.5](https://github.com/tw93/Pake/releases/tag/V2.3.5)

### System version

Apple M2 MacBook pro.

系统版本：14.2.1 (23C71)

### Node.js version

无

### Minimal reproduce step

下载[V2.3.5](https://github.com/tw93/Pake/releases/tag/V2.3.5) 里的xiaohongshu.dmg, 安装打开后，拖动标题栏，预期可以拖动，实际无法拖动

### What did you expect to see?

拖动标题栏，预期可以拖动，实际无法拖动

### What did you see instead?

拖动标题栏，预期可以拖动，实际无法拖动

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Fatedstar** [comment]
遇到相同情况，window11 64位系统，小红书进入后默认全屏，无法缩小窗口，使用起来有些不便

**Comment by tw93** [comment]
https://github.com/tw93/Pake/assets/8736212/2757359d-fa6c-4474-a74f-3c909a2675ee

应该和我的电脑版本差不多，请问其他app ok不，比如说微信读书，或许可以卸载以后，重新安装试试
