### ISSUE TITLE
[Bug]   error: invalid character `{` in package name: `tauri-plugin-{{name}}`, 

### ISSUE THREAD

**Issue by kknono** [tw93/Pake#696]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

@2.3.6

### System version

Mac M1

### Node.js version

v20.11.1

### Minimal reproduce step

for test "pake https://www.google.com --name Weekly --transparent"

### What did you expect to see?

Complete

### What did you see instead?

✔ Package installed!
✺ Building app...

> pake-cli@2.3.6 build
> npm run tauri build --release
✸ Building app...

> pake-cli@2.3.6 tauri
> tauri build
✹ Building app...
error: invalid character `{` in package name: `tauri-plugin-{{name}}`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)
 --> ../../../../../../../../.cargo/git/checkouts/plugins-workspace-fd0259fcb18f51ad/5b814f5/shared/template/Cargo.toml:2:8
  |
2 | name = "tauri-plugin-{{name}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^
✶ Building app...

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Depending on the update issue, and regenerating the lock file, you can try again.

**Comment by tw93** [comment]
npm i pake-cli -g 
Try again, version 2.3.8 is released!
