### ISSUE TITLE
macOS 关闭使用隐藏替代最小化

### ISSUE THREAD

**Issue by Skyxim** [tw93/Pake#697]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

最小化和关闭由于关闭的重写变成了同一个功能，在 macOS 上常见替代关闭的效果是隐藏

### Solution

```rust
 tauri::AppHandle::hide(&event.window().app_handle()).unwrap();
```

使用其可简单实现，将其他换成调之前的最小化代码

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Storm4542** [comment]
确实有这个情况

**Comment by tw93** [comment]
已经修复，最近发布一个版本
https://github.com/tw93/Pake/commit/7b94f5ba78e972ba52058f7d0b27a5ee2fa689bb#diff-2f5e0a90d4195e9986f5e24928dce16b59a80a2cf30f7059b38d55bd7d1eff69R49

**Comment by tw93** [comment]
npm i pake-cli -g

发布了 2.3.8 版本

**Comment by AlickH** [comment]
3.1.1版本好像又变成最小化了 不知道是不是我的问题
