### ISSUE TITLE
文章很长，前半部分字体正常，后半部分字体变大，无法看书

### ISSUE THREAD

**Issue by sufar** [tw93/Pake#7]
我的系统是Arch linux dwm，下面这个Fork，适配了linux:
https://github.com/ttys3/pake

但在使用过程中，某个章节内容很长，前面字体是正常的，后半部分出现字体变大：
<img width="664" alt="image" src="https://user-images.githubusercontent.com/82210712/195970844-95eb1a1f-8a22-47a7-8241-23e789fea083.png">

macOS会出现这个问题不？

**Comment by tw93** [comment]
你试试command ➕ r 刷新快捷键看看 那看起来和你系统的web容器有丢丢关系
mac 这边OK

**Comment by sufar** [comment]
> 你试试command heavy_plus_sign r 刷新快捷键看看 那看起来和你系统的web容器有丢丢关系 mac 这边OK

ctrl + r 和f5都没有反应，刷新不了

**Comment by sufar** [comment]
京东读书，https://e.m.jd.com/
后半部分没有这个问题：
<img width="655" alt="image" src="https://user-images.githubusercontent.com/82210712/195973727-d6f41138-4286-4c11-8361-b79ed7d7cc1a.png">

**Comment by tw93** [comment]
那应该和文档渲染本身有些关系了，先关了好了

**Comment by sufar** [comment]
> 那应该和文档渲染本身有些关系了，先关了好了
文档渲染？请问在哪关？

**Comment by tw93** [comment]
哈哈 你误解我的意思了，我的意思是说这个文档本身在webview里面渲染应该就有问题，我这边不好修复，就先将这个issue给关了，你可以打开你的默认浏览器，然后找到这一个文档看看有没有问题

**Comment by sufar** [comment]
> 

嗯，chrome里很正常，微信读书在webview有问题，不是这个项目的问题了

**Comment by sufar** [comment]
> 哈哈 你误解我的意思了，我的意思是说这个文档本身在webview里面渲染应该就有问题，我这边不好修复，就先将这个issue给关了，你可以打开你的默认浏览器，然后找到这一个文档看看有没有问题

试了下，在windows下，没有这个问题，但Arch Linux下有，下次再试试ubuntu，再有就给tauri提bug了
![image](https://user-images.githubusercontent.com/82210712/196077460-232f57a3-21be-4a32-bc2c-24191021c7f2.png)

**Comment by tw93** [comment]
👍  谢谢反馈

**Comment by sufar** [comment]
原因找到了，是我设置dpi的问题(The reason is the DPI issue)
我的Arch当时dwm的dpi被我调整过（I've tweaked the dpi for the Arch linux dwm）：

cat ~/.Xresources
`
#Xft.dpi: 188.68
Xft.dpi: 144

Xft.antialias: 1
Xft.hinting: 1
Xft.rgba: rgb
Xft.autohint: 0
Xft.hintstyle: hintfull
Xft.lcdfilter: lcdfilter
`
删除这个文件就好了(Just delete this file)，
现在正常了(It is normal now):
![image](https://user-images.githubusercontent.com/82210712/196082305-da0f0be1-be3a-47cf-9f99-4b5465a1bf56.png)
