### ISSUE TITLE
Is there a way to disable all shortcut?

### ISSUE THREAD

**Issue by diggerdu** [tw93/Pake#700]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

I'm using Pake to build a webshell client. However, the built app processes shortcuts in a way that conflicts with intended functions. For example, pressing Ctrl+R should access the command history of the shell, but instead, it triggers a page refresh.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by tw93** [comment]
Thanks for the feedback, I'll think about whether I can fix it by configuring the parameters

**Comment by tw93** [comment]
Please upgrade Pake-cli to the latest version 2.4.0 with the --disabled-web-shortcuts parameter, documentation is available at:
https://github.com/tw93/Pake/blob/dev/bin/README.md#disabled-web-shortcuts
