### ISSUE TITLE
twitter 滑动到最下面会导致推文消失

### ISSUE THREAD

**Issue by RekiDunois** [tw93/Pake#71]
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/23435534/200529464-89724d48-7d54-4c43-9a31-37fdacaa56d0.png">

我试过去掉twitter.css里的东西直接编译一个新的app，这个问题还是有

复现方式是用滚轮一直往下滚动，等他刷新两次到三次之后，推文就消失了，此时如果滚动回最开始，推文又会出现。

对页面进行放大似乎会增加这个问题的出现概率，不确定。

设备信息：

- Apple M1 Pro
- MacOS 13.0 (22A380)

**Comment by tw93** [comment]
谢谢反馈 我试试复现看 大概率Twitter本身适配问题

**Comment by tw93** [comment]
又试了试 找到了 是推特bug 你command 0 复原到原始大小就好了
