### ISSUE TITLE
需要一个 proxy option

### ISSUE THREAD

**Issue by bitQ2019** [tw93/Pake#710]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

比如访问 youtube ， 希望能够直接 proxy 不用开 global proxy

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
https://beta.tauri.app/references/config/#proxyurl

在最新的 `tauri@beta` 中已经支持了这个配置，但是有一些小限制（macos 版本），或许我们可以提供一个 `beta` 版的 `pake` 支持一下？

**Comment by jeasonnow** [comment]
> https://beta.tauri.app/references/config/#proxyurl
> 
> 在最新的 `tauri@beta` 中已经支持了这个配置，但是有一些小限制（macos 版本），或许我们可以提供一个 `beta` 版的 `pake` 支持一下？ @tw93

感觉是个大工程，得慢慢来

**Comment by tw93** [comment]
哈哈 是个大工程，我平时有去看2.0beta的东西，不过一直不正式版，想着正式版再来升级防止反复变跟

**Comment by bitQ2019** [comment]
👍👍👍👍

**Comment by assassinliujie** [comment]
> ### Search before asking
> * [x]  我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
>   I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.
> 
> ### Motivation
> 比如访问 youtube ， 希望能够直接 proxy 不用开 global proxy
> 
> ### Solution
> _No response_
> 
> ### Alternatives
> _No response_
> 
> ### Anything else?
> _No response_
> 
> ### Are you willing to submit a PR?
> * [x]  I'm willing to submit a PR!

nativefier有实习这个功能，不过nativefier已经停更了，而且只支持socks5和http代理。我拿来做了个内置代理的chatgpt应用

**Comment by jeasonnow** [comment]
[5752996f8925043fb5ac3bcf0cf82b92f47026b6](https://github.com/tw93/Pake/commit/5752996f8925043fb5ac3bcf0cf82b92f47026b6)

在实验性分支上支持了这个 option，可以试着使用一下，目前这个分支已经升级到了 tauri@2.x 版本，如果有其他的问题可以单独反馈下。

@bitQ2019

**Comment by hongfanmeng** [comment]
https://tauri.app/reference/config/#proxyurl

这个功能已经 stable了，考虑 merge 到主分支吗

**Comment by tw93** [comment]
终于支持了，可以使用 pake-cli 3.0.1 的版本，当前还在 experimental 分支，我这周会更新到main主干去

**Comment by IksGuo** [comment]
proxyUrl
string | null 格式为 uri

用于 WebView 所有网络请求的代理 URL。

必须是 http:// 或 socks5:// URL。


当我把这个配置项设置为："http://username:password@www.proxyurl.com:8080" 这种格式时，为什么在访问的时候还会要求输入代理的账号密码？
