### ISSUE TITLE
Pake添加指定语言

### ISSUE THREAD

**Issue by haitanghuadeng** [tw93/Pake#711]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

目前默认打包好的msi程序，默认语言是英语，能否增加指定语言的功能？非常感谢~

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
赞 https://github.com/tw93/Pake/pull/734
这个已经支持了，最近发布一个版本

**Comment by tw93** [comment]
pake-cli@2.6.0
