### ISSUE TITLE
Add support for cross site cookies

### ISSUE THREAD

**Issue by eznix86** [tw93/Pake#715]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

I wanted to turn idx.google.com into a desktop app. But it says, I cannot access the website unless I do this on mac.

I know tauri uses Webkit on mac, so the docs says:
https://developers.google.com/idx/guides/get-started#before-you-begin

Open Safari > Settings....
Turn off the following settings:

    Advanced > Block all cookies
    Privacy > Prevent cross-site tracking

So I believe there is no support for cross-site cookies ?

### Solution

Enable the support for cross site cookie. I saw an issue here, but not sure if it is related (#250)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Thanks for your feedback, I'll take a look

**Comment by jeasonnow** [comment]
https://github.com/tauri-apps/wry/issues/848

I found that this is an issue with `Tauri`. We might have to wait until this proposal is implemented...
