### ISSUE TITLE
打包提示成功了，但是下面报错了[Bug] 

### ISSUE THREAD

**Issue by 1024Boy** [tw93/Pake#716]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

![微信截图_20240523103937](https://github.com/tw93/Pake/assets/150877158/cf97dc9c-097f-4f0d-bf17-8900c9985343)

### System version

![微信截图_20240523103937](https://github.com/tw93/Pake/assets/150877158/cf97dc9c-097f-4f0d-bf17-8900c9985343)

### Node.js version

![微信截图_20240523103937](https://github.com/tw93/Pake/assets/150877158/cf97dc9c-097f-4f0d-bf17-8900c9985343)

### Minimal reproduce step

![微信截图_20240523103937](https://github.com/tw93/Pake/assets/150877158/cf97dc9c-097f-4f0d-bf17-8900c9985343)

### What did you expect to see?

![微信截图_20240523103937](https://github.com/tw93/Pake/assets/150877158/cf97dc9c-097f-4f0d-bf17-8900c9985343)

### What did you see instead?

![微信截图_20240523103937](https://github.com/tw93/Pake/assets/150877158/cf97dc9c-097f-4f0d-bf17-8900c9985343)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Tlntin** [comment]
大概率是命名问题，建议小写。

**Comment by yanlong-pan** [comment]
Same here! I tried to use lower cases, but that doesn't solve the problem as suggested by @Tlntin.

**Comment by Tlntin** [comment]
> Same here! I tried to use lower cases, but that doesn't solve the problem as suggested by @Tlntin.

Don't use blank char.
