### ISSUE TITLE
对于需要Google登录的网页会提示登录不安全，不让登录

### ISSUE THREAD

**Issue by Sadcatcat** [tw93/Pake#731]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

![image](https://github.com/tw93/Pake/assets/109957708/6af3d8da-5a01-40e8-aaf1-32bca731fcc6)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
和这个问题类似，暂时Pake这边无解，不过对于自己开发的应用的场景一般把谷歌登录代码里面的 ux_mode 设置为 redirect 就好了。

https://github.com/wavezync/vue3-google-signin/discussions/14
