### ISSUE TITLE
[Bug] 遇到有啟用「Cloudflare 傀儡程式管理」的服務會卡在人類驗證

### ISSUE THREAD

**Issue by bestpika** [tw93/Pake#737]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

v2.5.1

### System version

Windows 10 x64

### Node.js version

v21.7.0

### Minimal reproduce step

```
pake https://app.lunabot.ai/ --name Lunabot
```

### What did you expect to see?

正常使用該服務

### What did you see instead?

進入網站登入後會一直卡在人類驗證的畫面
我試過加上參數 `--safe-domain lunabot.ai,app.lunabot.ai` 沒有任何改變

### Anything else?

我檢查了 Webview2 的 UA 看起來跟一般的 Edge 一樣

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
```

以下是畫面截圖
![image](https://github.com/tw93/Pake/assets/5698157/754f8328-a008-4101-b1ff-8c2819da42fe)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
最近 Pake 升级了底层 tauri 到 2 了，辛苦试试 pake-cli 3.0.1 版本，我用 Mac 系统测试了一下你这边场景是 OK 的
<img width="1555" alt="image" src="https://github.com/user-attachments/assets/a744e28d-8a0c-4993-99bc-e57ec3a44412" />
