### ISSUE TITLE
能否支持JavaScript脚本注入

### ISSUE THREAD

**Issue by blysin** [tw93/Pake#739]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

想要调整某些网站的内容以使其更像正常的客户端程序。是否考虑提供类似于油猴脚本功能。允许注入自定义的JavaScript脚本,从而对网页内容进行调整和修改。

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tw93** [comment]
https://github.com/tw93/Pake/blob/master/bin/README.md#inject
看看这个
