### ISSUE TITLE
[Bug] When clicking the close button while the program is in full-screen mode, the entire screen turns black.

### ISSUE THREAD

**Issue by knowing-top** [tw93/Pake#740]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.5.1

### System version

macbook air  M1

### Node.js version

v19.8.1

### Minimal reproduce step

1.  clicking the close button while the program is in full-screen mode, the entire screen turns black.

### What did you expect to see?

exit, for example, to the desktop.

### What did you see instead?

black

### Anything else?

none

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by knowing-top** [comment]
<img width="1440" alt="Screenshot 2024-07-01 at 16 34 17" src="https://github.com/tw93/Pake/assets/173445895/0bb26155-6423-4405-9ab5-818a417b3dac">

**Comment by tw93** [comment]
Thank you for your feedback. It is indeed an underlying bug. I have fixed it in the dev code and will release an official version within this week.

**Comment by tw93** [comment]
pake-cli@2.6.0
