### ISSUE TITLE
支持离线网页应用打包吗

### ISSUE THREAD

**Issue by lonngxiang** [tw93/Pake#752]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

支持离线网页应用打包吗，没有在线网址

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xsran2008** [comment]
https://github.com/tw93/Pake/wiki/Pake%E6%89%93%E5%8C%85%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6%E7%A4%BA%E4%BE%8B
