### ISSUE TITLE
[Bug] mac 全屏下点x退出会黑，实际上应用没退出，体验不好，不知道是不是bug

### ISSUE THREAD

**Issue by lizhongyuan3** [tw93/Pake#753]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

master
1544b15ea67cbcab8b60e80cf5e10663331bf1cb

### System version

芯片：Apple M3 Pro
系统版本：macos 14.2.1 

### Node.js version

action 打包的

### Minimal reproduce step

1:在全屏模式下点击x
<img width="435" alt="image" src="https://github.com/user-attachments/assets/b0329ccd-ef18-4f60-87f1-032d656903fa">
2:就会看到
<img width="512" alt="image" src="https://github.com/user-attachments/assets/a9adc8c1-bf7e-4493-9392-bd59e9a06349">

### What did you expect to see?

退出或者其他正常的窗口

### What did you see instead?

黑色窗口

### Anything else?

无

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
https://github.com/electron/electron/issues/20263
和这个问题是类似的。

**Comment by jeasonnow** [comment]
https://github.com/electron/electron/issues/39572#issuecomment-1691431363

**Comment by tw93** [comment]
的确是Bug，我想了一个hack的办法 @jeasonnow 看看是不是这样更简单
https://github.com/tw93/Pake/blob/dev/src-tauri/src/main.rs#L70

@lizhongyuan3 最近发布一个版本修复一下，代码本身已经改好

**Comment by jeasonnow** [comment]
> 的确是Bug，我想了一个hack的办法 @jeasonnow 看看是不是这样更简单 https://github.com/tw93/Pake/blob/dev/src-tauri/src/main.rs#L70
> 
> @lizhongyuan3 最近发布一个版本修复一下，代码本身已经改好

简单粗暴。但是这个感觉是蛮 hack 的。当时看 oc 的写法应该可以对这种场景做一个比较好的拦截，但是还没搞出来，就先搁置了。

简单点说，在 macos 系统层面就对全屏模式下直接最小化的处理存在问题，所以我想到的解决办法就是
1.  监听是否在全屏模式下点击关闭。
2. 如果是则先退出全屏模式，再进行最小化。
3. 如果不是则走正常关闭逻辑。

`Tauri` 本身的 API 是不支持这样的操作的，所以需要用 `rust` 的 `cocoa` 和 `objc` 包来对 `tauri` 抛出的 `ns_window` 做更高阶的操作，我的代码里处理过一个版本，但是会对所有的退出全屏模式进行污染，所以我还需要一个标志位传输到 ns_window 内部用来判断是否该走特殊逻辑（在这一步我失败了）。你后续可以尝试一下这样写，我感觉会更好一点。 @tw93

**Comment by tw93** [comment]
哈哈 这个解法其实是我体验了一些mac app本身看到的处理，比如说apple music你可以试试😂

**Comment by jeasonnow** [comment]
我也试过，所以我想要的也是这样哈哈哈哈，只不过我当时考虑 fullscreen 的退出可能要等到所有的动画完成，这个时间点把不准，才想着走底层的回调看看，结果没成。

**Comment by tw93** [comment]
@jeasonnow 接下来版本我们一起来升级2.0 版本

最近发布了1.0版本最近的一个版本 pake-cli@2.6.0
