### ISSUE TITLE
[Bug] 打包完成，网页无法跳转，点击没有反应，windows

### ISSUE THREAD

**Issue by wylwangyalong** [tw93/Pake#757]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

打包完成，网页无法跳转，点击没有反应，windows

### System version

在github打包的

### Node.js version

在github打包的

### Minimal reproduce step

在github打包的

### What did you expect to see?

在github打包的

### What did you see instead?

在github打包的

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jaffliang** [comment]
链接如果是新窗口打开的就失败，还有confirm窗口也没有弹出来，直接就确认了

**Comment by JiuRanYa** [comment]
tauri内部不支持弹出新链接

**Comment by Sjj1024** [comment]
我使用tauri开发了一个界面化打包网页的软件，使用github云端编译：https://github.com/Sjj1024/PakePlus

**Comment by tw93** [comment]
试试最新的3.0.3版本，这里我做了一个优化
