### ISSUE TITLE
Add rpm support?

### ISSUE THREAD

**Issue by stone-w4tch3r** [tw93/Pake#759]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

For fedora, rhel, centos etc it would be great to have native packages instead of appimages

### Solution

Add rpm build option

### Alternatives

It is possible to use appimage, but it's integration into system is not perfect

### Anything else?

Anyway, thanks a lot for this tool!

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
https://github.com/tw93/Pake/tree/experimental 
在 experimental 增加了 rpm 打包格式的支持。

**Comment by tw93** [comment]
等到2.0 正式搞的时候就支持了，这个先关闭～

**Comment by tw93** [comment]
已经支持，请使用 pake-cli 3.0.1 版本
