### ISSUE TITLE
[enhancement] 在实验型分支升级目前使用的 tauri 版本到 2.x beta，方便后续的升级改造工作。

### ISSUE THREAD

**Issue by jeasonnow** [tw93/Pake#760]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

#### 1. 支持未来的跨平台应用需求
   - **动机**: 确保应用程序具备未来跨平台兼容性的能力，能够在不同操作系统上无缝运行。

#### 2. 支持更多有用的配置选项（如应用代理支持）
   - **动机**: 利用 Tauri 2.x 提供的新功能和配置选项，增强应用程序的功能性和灵活性，例如增加应用代理支持。

#### 3. 为后续大版本升级提供更平滑的过渡
   - **动机**: 通过当前的升级过程，为未来的大版本更新奠定基础，使其更加顺利和无缝，减少潜在的中断和兼容性问题。

#### 1. Support Future Cross-Platform Application Needs
   - **Motive**: Ensure the application can seamlessly run on various operating systems, preparing it for future cross-platform compatibility requirements.

#### 2. Support More Useful Configuration Options (e.g., Application Proxy Support)
   - **Motive**: Leverage new features and configuration options available in Tauri 2.x to enhance the application's functionality and flexibility, such as adding application proxy support.

#### 3. Provide a Smoother Transition for Future Major Upgrades
   - **Motive**: Establish a foundation for future major updates, making the upgrade process smoother and minimizing potential disruptions and compatibility issues.

### Solution

https://v2.tauri.app/start/migrate/from-tauri-1/

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jeasonnow** [comment]
https://github.com/tw93/Pake/tree/experimental

**Comment by jeasonnow** [comment]
> 赞 我感觉差不多到时间点了，趁着这个我们来做些升级以及新特性

我这个分支已经做完了大体的迁移和升级工作，目前使用之前的配置可以正常打包 `app`，但是还需要观察一下，目前增加了一个 `proxy` 的 `option `，可以试试看。

**Comment by tw93** [comment]
感谢大部分 @jeasonnow 的工作升级到 tauri2，当前我接着这个工作基本适配最新的完成了，这周来发布一个Pake 3.0 大版本
