### ISSUE TITLE
No text on title bar

### ISSUE THREAD

**Issue by grumphus** [tw93/Pake#763]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

The title bar having nothing but a small icon looks particularly odd especially when used with Groupy, an app that lets you turn windows into tabs. Screenshot of it in action below with Gmail being created by Pake, Google Sheets created by WebCatalog, and the third tab which is also Gmail created by Nativefier.

![image](https://github.com/user-attachments/assets/2e8f5199-999d-4d86-ba97-c8fffa97e9d6)

~~Also, the Gmail icon on the titlebar looks fuzzier compared to the Nativefier build which uses the exact same ico file. Is there a way to improve this?~~

### Alternatives

If you have [WindowManager](https://www.desksoft.com/WindowManager.htm) installed, you can fix the title bar issue yourself by  adding the Pake app's exe file to the WindowManager rule and enabling "On Open" in "Advanced" tab and using the TITLE ( "" ) command to set the title bar text whenever the Pake app launches.

### Anything else?

Thank you very much for this. I'm really impressed with how lightweight this solution is.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by grumphus** [comment]
Regarding the icon issue, I managed to fix the problem myself. Initially I used a PNG to ICO converter and saved only the 128x128 size. Nativefier uses ImageMagick to auto generate the other sizes. So I re-did the PNG to ICO converter and made a multi-size file including the smaller 16x16 sizes and rebuilt the Pake app using the updated ICO file and I resolved the issue. The title bar text issue still remains though I personally fixed it with a third-party app (see Alternatives).

Thank you!

**Comment by jeasonnow** [comment]
@grumphus 
https://github.com/tw93/Pake/blob/1d0628ed19dd8166e1bd3a2973812ebdf90a724e/src-tauri/src/app/window.rs#L27-L41

Since we don't yet support displaying the full title on Windows, maybe we could set the app name to windows.title in Windows? @tw93

**Comment by tw93** [comment]
You can add the logic of the title for the non-mac scene, free can directly add @jeasonnow

**Comment by rongrong1000** [comment]
I am looking forward to this feature very much
