### ISSUE TITLE
--single-instance option

### ISSUE THREAD

**Issue by grumphus** [tw93/Pake#765]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

I'd like to request a "--single-instance" option which restricts only one window of the app while still retaining the ability to "Open link in new window" via right-click on links.

My personal use case is for example, I move the pake-made app into a different monitor or Windows 11 virtual desktop and I have the pake app pinned to my taskbar. Clicking on the pinned app should bring focus to the already opened app on the different monitor or virtual desktop. Instead, it opens a new one.

Having a "--single instance" option can help people decide if they like or dislike this behavior. Thank you!

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Thank you for the feedback, I will take a look at this configuration, it seems quite necessary.

**Comment by grumphus** [comment]
Thank you very much! This is really my last major issue with Pake. After that, I'll make the full switch.

**Comment by grumphus** [comment]
Sir @tw93 . Do you have any update regarding this feature request? This is literally the only remaining feature I'd like to see. Thank you!

**Comment by tw93** [comment]
Please install pake-cli 3.0.3, which currently supports singleton mode by default.
Finally, I found a Windows machine to test. Sorry for the long wait.

**Comment by grumphus** [comment]
Thank you so much! Really grateful for your support and updates!

**Comment by grumphus** [comment]
Hello. I installed 3.0.3 and while it does keep it single-instance, it's so close to perfect.

Would it be possible if when launching the Pake packaged app while a single instance is open that the app comes to focus too? Sorry if that's too heavy of a request, but the other app to website solutions support that behavior.

Thank you!
