### ISSUE TITLE
[Bug] External link opens multiple duplicate tabs in default browser

### ISSUE THREAD

**Issue by grumphus** [tw93/Pake#766]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.5.2

### System version

Windows 11 build 22631.3880

### Node.js version

20.16.0

### Minimal reproduce step

Create Feedly or Gmail app out of feedly.com/gmail.com with name and icon parameters.
Install and run Feedly/Gmail.
Log into account
Click on any Feedly news link or link within a Gmail message

### What did you expect to see?

Link is opened on the default browser

### What did you see instead?

Three of the same link on Feedly opened on the default browser; two of the same link on Gmail.

### Anything else?

I tested the same Feedly app on a touchscreen Windows 11 computer and tapping the link reproduces the issue.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

EDIT 8/5/2024: Originally titled "External link opens three of the same tab". I modified the post to reflect a slightly different behavior with the Gmail app I made with Pake.

**Comment by i0Ek3** [comment]
Same issue on Apple Silicon MacBook Pro. A brief look at the code locates these "guys": `detectDownloadByCreateAnchor()`, `handleExternalLink()` and const `detectAnchorElementClick`, not sure if it's caused here. @tw93

**Comment by grumphus** [comment]
> Same issue on Apple Silicon MacBook Pro. A brief look at the code locates these "guys": `detectDownloadByCreateAnchor()`, `handleExternalLink()` and const `detectAnchorElementClick`, not sure if it's caused here. @tw93

Thanks for confirming! How many tabs does it open? For some reason, with the Gmail app I made, an external link creates two tabs while Feedly creates three. I will modify my original post to reflect.

**Comment by i0Ek3** [comment]
> > Same issue on Apple Silicon MacBook Pro. A brief look at the code locates these "guys": `detectDownloadByCreateAnchor()`, `handleExternalLink()` and const `detectAnchorElementClick`, not sure if it's caused here. @tw93
> 
> Thanks for confirming! How many tabs does it open? For some reason, with the Gmail app I made, an external link creates two tabs while Feedly creates three. I will modify my original post to reflect.

In my case, three tabs were created for both macosicons.com and Instagram. Plus, I use Google Chrome.
