### ISSUE TITLE
能否添加强制dark模式，类似调整prefers-color-scheme的方式

### ISSUE THREAD

**Issue by zjzoze** [tw93/Pake#767]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

能否添加强制dark模式，类似调整perfers-color-scheme的方式，谢谢大神~

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
已经支持，请这周发布一个版本，文档使用是这样的，不过只支持mac系统
https://github.com/tw93/Pake/blob/dev/bin/README_CN.md#dark-mode

**Comment by xinmans** [comment]
windows下能支持吗？小红书，YouTube这些希望有dark模式
