### ISSUE TITLE
cant login twitter with google

### ISSUE THREAD

**Issue by SedationH** [tw93/Pake#77]
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/56129212/201232482-ca99f15b-6e22-4e83-8325-3335a1c05450.png">

the login window didn jump out

**Comment by tw93** [comment]
Thank you for your feedback. I'll check it out.

**Comment by tw93** [comment]
I have a look. Here, Twitter uses the mode of opening a new window. Sorry, it doesn't support it. You can log in with your user name.
