### ISSUE TITLE
[Bug] No notifications for instagram

### ISSUE THREAD

**Issue by ishaanrathodd** [tw93/Pake#779]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.5.2

### System version

macOS Sonoma 14.6

### Node.js version

v18.18.2

### Minimal reproduce step

just no notifications lol

### What did you expect to see?

notifications

### What did you see instead?

nothing

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ishaanrathodd** [comment]
@tw93 is this even possible? as far as ik instagram doesn't support notifications for safari, only chrome does. And none of the web2app converters support instagram notifications.

**Comment by tw93** [comment]
Your understanding should be correct, but this needs to be tested. I remember that Pake has upgraded compatibility for notifications, and you can even find a simple demo scenario to test it out.
