### ISSUE TITLE
能提供英文版本的Youtube和Google Translate吗？

### ISSUE THREAD

**Issue by zdrjson** [tw93/Pake#78]

**Comment by tw93** [comment]
这个取决于你个人的设置即可，在这里
<img width="378" alt="image" src="https://user-images.githubusercontent.com/8736212/201502065-37667b1a-5167-4101-9812-b67fadd7f53c.png">

**Comment by zdrjson** [comment]
设置了英语的，电脑也是设置了英语的。下载了dmg安装是中文的。

**Comment by zdrjson** [comment]
Google Translate不能设置。

**Comment by tw93** [comment]
点击头像 进去个人信息
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/8736212/201529623-9c7ba83b-f008-4f2f-9ffe-88d2e8a8be1f.png">

**Comment by zdrjson** [comment]
你这个是网页版吧？我下载你的dmg，然后安装后使用。没有可以点击进入个人信息切换功能。

<img width="1155" alt="Screen Shot 2022-11-14 at 16 10 35" src="https://user-images.githubusercontent.com/9263473/201608585-a69c3f28-3ee9-4a3f-8d91-fb19e0054bcc.png">

**Comment by tw93** [comment]
点错了 谷歌翻译在右上角

**Comment by zdrjson** [comment]
右边头像点击进入不了个人信息页面 你的可以吗？

**Comment by tw93** [comment]
搞好了
下载这个最新包 https://github.com/tw93/Pake/releases/download/V0.9.0/GoogleTranslate.dmg
然后网页打开这个 https://myaccount.google.com/language?continue=https%3A%2F%2Fmyaccount.google.com%2Fpersonal-info%3Fhl%3Dzh_CN
将你的谷歌设置成英语就好了

**Comment by zdrjson** [comment]
嗯，谢谢。
网页版没有问题。

**Comment by tw93** [comment]
应该你设置完以后 回到Pake 刷新就好了
