### ISSUE TITLE
Add shortcut button to borderless fullscreen (equivalent of F11 on browsers)

### ISSUE THREAD

**Issue by vampywiz17** [tw93/Pake#782]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

Some apps need to use on borderless fullscreen mode. 

### Solution

Browsers are support it, so i think it possible to integrate it.

### Alternatives

-

### Anything else?

-

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
This is supported now, but the shortcut I use more commonly is `Control + Command + F`,Then double-click the title bar to go full screen.
However, I did not consider the F11 shortcut key for Windows. I added it in the latest version.
