### ISSUE TITLE
请求添加对 env(safe-area-inset-top) 支持

### ISSUE THREAD

**Issue by mkdirnow** [tw93/Pake#783]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

<img width="500" alt="image" src="https://github.com/user-attachments/assets/fedac144-6194-4f54-9a2c-2d5a284aaf95">

不知道能不能实现，因为如果使用固定高度，在非 pake app 中就会有点突兀，如果将标题栏高度作为安全区域数值则可以都兼容到

🖖

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
这种情况建议用有标题栏的方式
你说的这种我试试

**Comment by tw93** [comment]
试了试不太行，这里假如需要使用隐藏头部的功能，还有一种解法，注入css
https://github.com/tw93/Pake/blob/master/bin/README.md#inject
还有一种解法，就是在原始代码里面判断 window.pakeConfig 是否存在，然后简单兼容一下
