### ISSUE TITLE
招远程前端开发，中高级，15k-25k，远程岗位需要接受测试

### ISSUE THREAD

**Issue by foya6** [tw93/Pake#784]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

telegram@HR606060
 
aoke8686@gmail.com
![image](https://github.com/user-attachments/assets/2440d6fe-0d35-42a1-8fd7-ed7a5fa00dfb)

### System version

1

### Node.js version

1

### Minimal reproduce step

1

### What did you expect to see?

1

### What did you see instead?

1

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
无关 关掉
