### ISSUE TITLE
建一个微信群，让开发者和用户可以实时交流反馈

### ISSUE THREAD

**Issue by chmod777john** [tw93/Pake#798]
这个工具有希望和 electron 竞争，如果要做成一个大家喜欢的样子的话，一个用户社群是必不可少的，开发者互相之间可以实时交流激发 idea ，有些好的 feature 可能是闲聊时发现的。

若项目团队需要，我可以把群管理转让回给你们 

![image](https://github.com/user-attachments/assets/b48bcdd3-2f93-4fec-9fd4-85a461690180)

若群聊二维码过期失效，可联系微信号 drinking-soda

**Comment by tw93** [comment]
抱歉，很推荐开源通过issue和讨论组的方式来讨论问题，这样会简单方便不少（哈哈，当然是对于开发者而言....
https://tw93.fun/2023-09-18/open.html
