### ISSUE TITLE
可以把微信阅读插件打包进去吗

### ISSUE THREAD

**Issue by fsafaf** [tw93/Pake#8]
主要是想要导出笔记的功能， 插件的地址是这个   https://weread.qnmlgb.tech/chrome

**Comment by tw93** [comment]
https://github.com/tauri-apps/tauri/discussions/2685
<img width="937" alt="image" src="https://user-images.githubusercontent.com/8736212/196013573-1cd7864a-453f-442b-b87b-efdb00221323.png">
官方答案是不行

**Comment by fsafaf** [comment]
有点遗憾，不过也挺好用的，比切换浏览器标签方便
