### ISSUE TITLE
How to build for Windows (MacOS) from Linux (amd64)

### ISSUE THREAD

**Issue by mrmuminov** [tw93/Pake#806]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

How to build app for another operation systems (windows, macos) from linux (ubuntu or another)?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by aadityaverma** [comment]
Tauri v2 supports mobile ios and android packaging too

**Comment by tw93** [comment]
Maybe you can try Pake github actions
https://github.com/tw93/Pake/wiki/Online-Compilation-(used-by-ordinary-users)
