### ISSUE TITLE
能否提供触控板双手滑动前进后退和鼠标按钮前进后退，类似网页端的体验

### ISSUE THREAD

**Issue by LeeeSe** [tw93/Pake#81]
经测试无法在app中利用鼠标按钮和触控板快速前进和后退
希望能够支持

**Comment by tw93** [comment]
主要是哪一个App 方便说一下名称吗？我拿着那个去测试

**Comment by LeeeSe** [comment]
v2ex.app
reference.app
系统：MacOS 13.1 Beta版
