### ISSUE TITLE
后续是否考虑加入APK安装文件的打包支持

### ISSUE THREAD

**Issue by emotions001** [tw93/Pake#817]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

目前Win、Mac、Linux都支持了，后续是否有加入对安卓设备的打包支持的计划？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by cxplay** [comment]
https://github.com/tw93/Pake/issues/666
