### ISSUE TITLE
Update dependencies to tauri 2.0 and support iOS and Android

### ISSUE THREAD

**Issue by brandonxiang** [tw93/Pake#819]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

Nowdays, tauri has already upgraded to 2.0 and supported Mobile. We also look forward to supporting ship website to iOS and Android.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by BruceLee569** [comment]
+1 😘

**Comment by mdabir1203** [comment]
Is there a possibility to do a PR for this?

**Comment by tw93** [comment]
https://github.com/tw93/Pake/releases/tag/V3.0.3

The upgrade to Tauri 2.0 has been completed, and a lot of compatibility work has been done. However, I plan to support iOS and Android later, as I haven't figured out the best way to distribute it yet.
