### ISSUE TITLE
请问现在支持打开多个应用实现数据隔离吗

### ISSUE THREAD

**Issue by yike510** [tw93/Pake#824]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

打开多个exe应用时实现数据隔离

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by yike510** [comment]
我希望打每打开一个应用窗口都是单独的数据，而默认读取的数据是第一个打开的应用窗口数据，也就是说第一次打开时共享的是默认数据，后面打开的是单独的数据

**Comment by BA7IEE** [comment]
我也在赵这个功能，没找到，我两个账户 打包两个应用，数据是一样的

**Comment by tw93** [comment]
试试修改一下 identifier 这个字段，让两个不是一个
此外有没有测试的case，我也打包来测试测试
