### ISSUE TITLE
[Bug] 使用GitHub actions里的pake cli打包的https://t.kuaitu.cc/功能不完整。

### ISSUE THREAD

**Issue by GaoHaHa-IronMan** [tw93/Pake#827]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

2.6.1

### System version

macOS 14.7

### Node.js version

node: v18.20.4

### Minimal reproduce step

实际运行的action配置https://github.com/GaoHaHa-IronMan/Pake/actions/runs/11397764970
cli运行时只指定了name和icon参数，其他都是默认。

### What did you expect to see?

在番茄时钟倒计时结束后点击弹出框后应该停止闹钟声音

### What did you see instead?

在番茄时钟倒计时结束后点击弹出框后没有停止闹钟，除非右键reload或者退出程序

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
谢谢反馈，这个番茄时钟做得很好看。
我刚刚用最新的 pake-cli 3.0.1 版本测试了一下，效果是符合预期的，请升级后试试看。
<img width="1555" alt="image" src="https://github.com/user-attachments/assets/1b83c2cd-9231-4c56-9dee-5759f80abf86" />
