### ISSUE TITLE
Implement vditor application with Pake

### ISSUE THREAD

**Issue by datgausaigon** [tw93/Pake#835]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

Hi, 

I love vditor https://github.com/Vanessa219/vditor. Thanks to vditor for creating it.

I have been using the markdown-editor https://github.com/shuzijun/markdown-editor Plugin for the JetBrains IDE. This plugin implements vditor into JetBrains IDEs (IntelliJ IDEA, PHPStorm, etc.).

I am looking forward to having a Desktop App that runs Cross Platform (Windows, macOS, Linux) to create and edit Markdown files on the computer, vditor.

Can you implement this with Pake? This is a great demonstration of Pake's application if successful..

Thanks 
🐻

**Comment by tw93** [comment]
You can try my other work, Miaoyan, a markdown note-taking application, which is a bit more user-friendly than this one.

> <https://miaoyan.app/>

**Comment by datgausaigon** [comment]
Hi @tw93 ,

Thanks for your reply.

Your app is great. But it's only for macOS right now. I'm currently developing for a team that uses multiple platforms and operating systems (Windows, macOS, Linux). It would be great if your app was cross-platform.

Thanks 
🐻
