### ISSUE TITLE
[Bug]  pake url options case error

### ISSUE THREAD

**Issue by icai** [tw93/Pake#853]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

pake -v
2.6.1

### System version

osc

### Node.js version

v20.10.0

### Minimal reproduce step

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/FabianLars/tauri-plugin-oauth' '+refs/heads/main:refs/remotes/origin/main'` (exit status: 128)
       Error failed to build app: failed to build app
file:///Users/terry/.local/bin/global/5/.pnpm/pake-cli@2.6.1/node_modules/pake-cli/dist/cli.js:374
                reject(new Error(`${code}`));
                       ^

Error: 1

### What did you expect to see?

fix fetch error https://github.com/FabianLars/tauri-plugin-oauth ?

### What did you see instead?

https://github.com/FabianLars/tauri-plugin-oauth' '+refs/heads/v2:refs/remotes/origin/v2

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Thanks for your feedback, please use pake-cli 3.0.1
Recently, the bottom floor has undergone a major upgrade.
https://github.com/tw93/Pake/blob/main/docs/cli-usage.md#
