### ISSUE TITLE
Allow Geolocations services

### ISSUE THREAD

**Issue by vmador** [tw93/Pake#861]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

Many web applications require geolocation services to function properly. Currently, when packaging web applications with Pake that use geolocation, the permission prompt doesn't appear and the geolocation API is not accessible. This limits the functionality of web apps that rely on location services.

### Solution

Add support for system permissions, specifically geolocation services. This could be implemented by:

Adding a configuration option in Pake to enable geolocation permissions
Properly handling system permission requests
Allow passing these permissions through to the webview component
Adding documentation about how to enable and use geolocation in Pake apps

### Alternatives

The implementation could:

Add a new flag --enable-permissions or specific --enable-geolocation
Modify the underlying Tauri configuration to allow geolocation access
Handle the necessary entitlements for macOS builds
Ensure proper permission handling across different operating systems

pake https://example.com \
--name "MyApp" \
--enable-geolocation

### Anything else?

This is particularly important for web apps that use mapping services or location-based features
Current workarounds like using IP-based geolocation are not as accurate or reliable
Similar functionality exists in Tauri, which Pake is built upon

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
Thank you for suggesting the location feature. It's actually quite good, but currently, I see that the vast majority of PC web scenarios do not support location capabilities. Then I referenced tauri-plugin-geolocation and found that it only supports mobile versions. I plan to add this when Pake supports mobile versions. If you find a location capability for PC scenarios, feel free to submit a PR.
