### ISSUE TITLE
页面元素不支持拖拽

### ISSUE THREAD

**Issue by fts11259375** [tw93/Pake#862]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

我用了vuedraggableplus这个库，发现在pake打包的程序里无法拖拽html元素，有什么办法可以实现拖拽么？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
发布了 Pake-cli 3.0.0 版本，默认支持了这个属性，不需要配置，此外还更新了不少底层能力，去试试
