### ISSUE TITLE
[Bug] windows打包报错failed to bundle project: error running candle.exe

### ISSUE THREAD

**Issue by pengwon** [tw93/Pake#869]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

❯ pake -v
3.0.0-beta

### System version

windows 10 19045

### Node.js version

❯ node -v && npm -v
v16.18.0
8.19.2

### Minimal reproduce step

pake https://uarix.github.io/nRF51-EPD/ --name epd

### What did you expect to see?

打包成功

### What did you see instead?

> tauri build

   Compiling pake v0.1.0 (C:\Users\yp.wang\AppData\Roaming\npm\node_modules\pake-cli\src-tauri)
    Finished `release` profile [optimized] target(s) in 54.19s
    Built application at: C:\Users\yp.wang\AppData\Roaming\npm\node_modules\pake-cli\src-tauri\target\release\pake.exe
    Info Target: x64
    Running candle for "main.wxs"
failed to bundle project: error running candle.exe: `failed to run C:\Users\yp.wang\AppData\Local\tauri\WixTools314\candle.exe`
    Error failed to bundle project: error running candle.exe: `failed to run C:\Users\yp.wang\AppData\Local\tauri\WixTools314\candle.exe`
file:///C:/Users/yp.wang/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:361
                reject(new Error(`${code}`));
                       ^

Error: 1
    at file:///C:/Users/yp.wang/AppData/Roaming/npm/node_modules/pake-cli/dist/cli.js:361:24
    at C:\Users\yp.wang\AppData\Roaming\npm\node_modules\pake-cli\node_modules\shelljs\src\exec.js:145:9
    at ChildProcess.exithandler (node:child_process:410:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

### Anything else?

使用GitHub actions报同样的错误

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by pengwon** [comment]
使用 pake-cli@2.6.1 没有问题

**Comment by fts11259375** [comment]
我也有同样的错误

**Comment by tw93** [comment]
谢谢反馈，请使用 pake-cli@3.0.1，底层对应 main.wxs 有更新导致。
辛苦帮忙看看是不是OK的，我在云端测试了一些

**Comment by pengwon** [comment]
> 谢谢反馈，请使用 pake-cli@3.0.1，底层对应 main.wxs 有更新导致。 辛苦帮忙看看是不是OK的，我在云端测试了一下，已经修复 @fts11259375 @pengwon

感谢耐心解答。我在本地测试已经修复。
