### ISSUE TITLE
[Bug] 3.0安装后打开应用，无法关闭，只能在任务管理器里关闭进程

### ISSUE THREAD

**Issue by tim-wang-tmp** [tw93/Pake#870]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

3.0

### System version

Win11 dev 26120.1252

### Node.js version

无

### Minimal reproduce step

打开应用后可以浏览，点击关闭时整个界面卡死无反应，电脑其他程序也没有反应

### What did you expect to see?

点击关闭就可以退出

### What did you see instead?

程序无响应，托盘的退出也无反应

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ml1990s** [comment]
一样的问题

**Comment by tw93** [comment]
谢谢反馈 我今天看看

**Comment by pengwon** [comment]
也遇到这个问题了，并且v3.0.1打的包比v2.6.1大，可执行文件也略大。

**Comment by tw93** [comment]
我手上没有windows机器，试了试不太好复现，我在想有没有小伙伴电报联系我一下，我们联调复现一下问题，我的电报 @HiTw93
@pengwon @ml1990s @tim-wang-tmp

**Comment by tim-wang-tmp** [comment]
> 我手上没有windows机器，试了试不太好复现，我在想有没有小伙伴电报联系我一下，我们联调复现一下问题，我的电报 @HiTw93 @pengwon @ml1990s @tim-wang-tmp

加你了

**Comment by tw93** [comment]
终于修复了，大伙试试效果，同时cli也是3.0.3版本
https://github.com/tw93/Pake/releases/tag/V3.0.3
