### ISSUE TITLE
在github action打包添加最大化和最小化选项

### ISSUE THREAD

**Issue by fcwys** [tw93/Pake#877]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

在github action打包添加最大化和最小化选项，目前在打包选项内没有全屏、最大化、最小化选项，希望能支持，非常感谢！

### Solution

无

### Alternatives

无

### Anything else?

无

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tw93** [comment]
非常建议使用 pake-cli 的方案，这里不考虑加到github action里面是由于本身这个渠道是给小白同学使用，参数太多了，会让这个东西很复杂，pake cli 里面可以放不少隐藏参数，可以去翻翻文档，这里我理解你需要的是全屏的这个功能

**Comment by fcwys** [comment]
不是全屏，只是最大化窗口，这个已经解决了，目前棘手的是下载改不了路径和没法设置下载都弹框提示保存的问题，目前经过测试只有python的pywebview实现了，pake的打包试过暂时没法
