### ISSUE TITLE
请大佬帮忙给boss直聘win打包下https://www.zhipin.com/

### ISSUE THREAD

**Issue by lingok1** [tw93/Pake#878]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

请大佬帮忙给boss直聘win打包下https://www.zhipin.com/

### Solution

请大佬帮忙给boss直聘win打包下https://www.zhipin.com/

### Alternatives

请大佬帮忙给boss直聘win打包下https://www.zhipin.com/

### Anything else?

请大佬帮忙给boss直聘win打包下https://www.zhipin.com/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by starsdream666** [comment]
[Uploading BOSS直聘.zip…]()

**Comment by starsdream666** [comment]
[BOSS直聘.zip](https://github.com/starsdream666/Pake/actions/runs/12493713870/artifacts/2361516575)
