### ISSUE TITLE
🔴「witeboard」希望增加网页的支持

### ISSUE THREAD

**Issue by Thomas-Harrell** [tw93/Pake#9]
https://witeboard.com/

![SCR-20221016-pw1](https://user-images.githubusercontent.com/106761803/196030784-3d452930-345a-4a39-963b-504ca8112fd8.png)

**Comment by tw93** [comment]
用了下挺好用的，谢谢推荐

### Witeboard

下载地址：<https://tw93.fun/images/app/Witeboard.dmg>
![4](https://gw.alipayobjects.com/zos/k/mq/SCR-20221016-uv9.png)
