### ISSUE TITLE
打包window提示错误 error: linker `link.exe` not found

### ISSUE THREAD

**Issue by ankylau** [tw93/Pake#96]
您好，MAC M1 打包 window版本 提示：

error: linker `link.exe` not found
  |
  = note: No such file or directory (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017, VS 2019 or VS 2022 was installed with the Visual C++ option

error: could not compile `app` due to previous error
       Error failed to build app: failed to build app

打包MAC app 正常打包。

**Comment by pan93412** [comment]
需要用 `cross` 進行跨平台打包。

**Comment by ankylau** [comment]
> 需要用 `cross` 進行跨平台打包。

能具体说一下怎么操作吗？

**Comment by shunyue1320** [comment]
中国朋友可以参考这个：

1. 确保安装了：https://visualstudio.microsoft.com/zh-hans/visual-cpp-build-tools/
![企业微信截图_16699531464778](https://user-images.githubusercontent.com/47295879/205212289-43bfd717-f8f2-4d81-9d04-26b925b7b5c1.png)

2. 修改 tauri.conf.json
```js
"bundle": {
"windows": {
    "wix": {
      "language": "zh-CN" // 语言修改成中文
    }
  }
}
```
https://github.com/tauri-apps/tauri/issues/1976

**Comment by lanbosm** [comment]
同求如何解决 mac怎么装c++布丁 作者能看下https://gist.github.com/Mefistophell/9787e1b6d2d9441c16d2ac79d6a505e6 有解吗

**Comment by niuhuheyi** [comment]
good thankyou you idea
