### ISSUE TITLE
如何屏蔽google adsense的穿插全屏广告呢？

### ISSUE THREAD

**Issue by ankylau** [tw93/Pake#99]
首次点击链接后会弹出一个google adsense的全屏穿插广告，应该怎样去掉呢？ CSS我好像去不掉。

**Comment by tw93** [comment]
有没有链接 给我一个看看

**Comment by tw93** [comment]
教你一招，在浏览器用去广告插件 比如说 https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm
看用了在浏览器里面去广告广告是不是被干掉了，假如干掉了，可以打开chrome调试，看他的样式怎么写的来屏蔽

**Comment by ankylau** [comment]
好的，感谢！我去试试～
